<?php
/**
 * Printable Sales Orders Report supporting Khmer and English language modes.
 * Uses high quality HTML print preview with web font support and native browser print capability.
 */
require 'auth.php';
require 'config.php';
require_once 'lang.php';
require_once 'dompdf/dompdf/autoload.inc.php';

use Dompdf\Dompdf;
use Dompdf\Options;

if (!can('report') && !can('report_sale') && !can('report_employee')) { header("Location: dashboard.php?denied=1"); exit; }

date_default_timezone_set('Asia/Phnom_Penh');

function he($s) { return htmlspecialchars((string)$s, ENT_QUOTES, 'UTF-8'); }

// ── Language Detection ──
$lang = is_string($_GET['lang'] ?? null) ? trim($_GET['lang']) : current_lang();
$isKm = ($lang === 'km');

$lbl_cafe_title   = 'The Bird Nest Café';
$lbl_report_sale  = $isKm ? 'របាយការណ៍លក់' : 'Report Sale';
$lbl_period       = $isKm ? 'រយៈពេល:' : 'Period:';
$lbl_to           = $isKm ? 'ដល់' : 'to';
$lbl_generated    = $isKm ? 'បង្កើតនៅ:' : 'Generated:';
$lbl_generated_by = $isKm ? 'បង្កើតដោយ:' : 'Generated by:';
$lbl_table_title  = $isKm ? 'តារាងរបាយការណ៍ការលក់' : 'SALES ORDERS REPORT TABLE';

$lbl_col_no       = $isKm ? 'លេខ Order' : 'No Order';
$lbl_col_date     = $isKm ? 'កាលបរិច្ឆេទ' : 'Date';
$lbl_col_cust     = $isKm ? 'អតិថិជន' : 'Customer';
$lbl_col_price    = $isKm ? 'តម្លៃ' : 'Price';
$lbl_col_qty      = $isKm ? 'ចំនួនទំនិញ' : 'Qty Item';
$lbl_col_total    = $isKm ? 'ចំណូល' : 'Revenue';
$lbl_col_cogs     = $isKm ? 'ដើមទុន' : 'COGS';
$lbl_col_profit   = $isKm ? 'ប្រាក់ចំណេញ' : 'Profit';
$lbl_col_curr     = $isKm ? 'រូបិយប័ណ្ណ' : 'Currency';
$lbl_col_place    = $isKm ? 'អ្នកលក់' : 'Place by';
$lbl_col_sum      = $isKm ? 'សរុប' : 'Total';

$lbl_date_from    = $isKm ? 'ចាប់ពីថ្ងៃ:' : 'Date From:';
$lbl_date_to      = $isKm ? 'ដល់ថ្ងៃ' : 'Date to';
$lbl_doc_no       = $isKm ? 'Doc No :' : 'Doc No :';

$lbl_gross_sales  = $isKm ? 'ចំណូលសរុបដើម' : 'Total Gross Sales';
$lbl_total_items  = $isKm ? 'ទំនិញសរុប' : 'Total Item';
$lbl_net_revenue  = $isKm ? 'ចំណូលសុទ្ធសរុប' : 'Total Net Revenue';
$lbl_total_cogs   = $isKm ? 'ដើមទុនសរុប' : 'Total COGS';
$lbl_total_profit = $isKm ? 'ប្រាក់ចំណេញសរុប' : 'Total Profit';

// ── Date validation ──
$today = business_date_today();
$date  = is_string($_GET['date'] ?? null) ? trim($_GET['date']) : '';
if (!preg_match('/^(\d{4})-(\d{2})-(\d{2})$/', $date, $m) || !checkdate((int)$m[2], (int)$m[3], (int)$m[1])) {
    $date = $today;
}
if ($date > $today) { $date = $today; }

// ── Range mode ──
$dateFrom = is_string($_GET['date_from'] ?? null) ? trim($_GET['date_from']) : '';
$dateTo   = is_string($_GET['date_to']   ?? null) ? trim($_GET['date_to'])   : '';
$isRange  = false;
if ($dateFrom !== '' && $dateTo !== '') {
    if (preg_match('/^\d{4}-\d{2}-\d{2}$/', $dateFrom) && preg_match('/^\d{4}-\d{2}-\d{2}$/', $dateTo)) {
        if ($dateFrom <= $dateTo && $dateTo <= $today) { $isRange = true; }
    }
}

// ── Table report orders & filters ──
$filter_from    = trim($_GET['date_from'] ?? $_GET['from_date'] ?? ($isRange ? $dateFrom : $date));
$filter_to      = trim($_GET['date_to']   ?? $_GET['to_date']   ?? ($isRange ? $dateTo   : $date));
$filter_payment = trim($_GET['payment_method'] ?? '');
$_is_mgr = in_array($_SESSION['role'] ?? '', ['admin', 'manager']);
$filter_user = (int)($_GET['user_id'] ?? $_GET['user'] ?? 0);
if (!$_is_mgr) {
    $filter_user = (int)$_SESSION['user_id'];
}

if (!preg_match('/^\d{4}-\d{2}-\d{2}$/', $filter_from)) $filter_from = $today;
if (!preg_match('/^\d{4}-\d{2}-\d{2}$/', $filter_to))   $filter_to   = $today;
if ($filter_from > $filter_to) [$filter_from, $filter_to] = [$filter_to, $filter_from];

$where_conds = ["o.business_date BETWEEN '$filter_from' AND '$filter_to'"];
if ($filter_payment !== '') {
    $where_conds[] = "o.payment_method = '" . $conn->real_escape_string($filter_payment) . "'";
}
if ($filter_user > 0) {
    $where_conds[] = "(o.user_id = $filter_user OR o.employee_id = $filter_user)";
}
$where_str = implode(' AND ', $where_conds);

$_gen_role = ucfirst($_SESSION['role'] ?? 'Admin');
$_gen_name = $_SESSION['emp_name'] ?? $_SESSION['username'] ?? 'Admin';
$gen_by_str = (strtolower($_gen_role) !== strtolower($_gen_name)) ? "{$_gen_role} ({$_gen_name})" : $_gen_name;

$sql_table_orders = "SELECT o.order_id, o.daily_order_no, o.order_date, o.customer_name, o.table_number, o.order_type, o.total, o.payment_method, o.status,
                            IFNULL(o.promotion_discount, 0) + IFNULL(o.manual_discount, 0) AS discount_amount,
                            u.username as staff_name 
                     FROM orders o 
                     LEFT JOIN users u ON u.user_id = o.user_id 
                     WHERE $where_str 
                     ORDER BY o.order_id ASC";
$res_table_orders = $conn->query($sql_table_orders);
$table_orders = $res_table_orders ? $res_table_orders->fetch_all(MYSQLI_ASSOC) : [];

// Compute per-order COGS for COGS & Profit columns
$cogsByOrder = [];
if ($table_orders) {
    $tbl_order_ids = array_map(fn($o) => (int)$o['order_id'], $table_orders);
    $in_ids = implode(',', $tbl_order_ids);
    $cost_map_ref = ingredient_cost_map($conn);
    
    $q_its = $conn->query("
        SELECT oi.order_id, oi.product_id, oi.milk, oi.quantity
        FROM order_items oi
        WHERE oi.order_id IN ($in_ids)
    ");
    $items_by_order = [];
    $pids_map = [];
    if ($q_its) {
        while ($it = $q_its->fetch_assoc()) {
            $items_by_order[(int)$it['order_id']][] = $it;
            if ((int)$it['product_id'] > 0) { $pids_map[(int)$it['product_id']] = true; }
        }
    }
    
    $recipes_map = [];
    if ($pids_map) {
        $pin_str = implode(',', array_keys($pids_map));
        $qr_rec = $conn->query("
            SELECT pi.product_id, pi.ingredient_id, pi.amount_used, i.ingredient_name
            FROM product_ingredients pi
            JOIN ingredients i ON i.ingredient_id = pi.ingredient_id
            WHERE pi.product_id IN ($pin_str)
        ");
        if ($qr_rec) {
            while ($r = $qr_rec->fetch_assoc()) {
                $recipes_map[(int)$r['product_id']][] = [
                    'ingredient_id'   => (int)$r['ingredient_id'],
                    'ingredient_name' => $r['ingredient_name'],
                    'amount_used'     => (float)$r['amount_used'],
                ];
            }
        }
    }

    foreach ($items_by_order as $oid => $its) {
        $ocost = 0.0;
        foreach ($its as $it) {
            $pid  = (int)$it['product_id'];
            $qty  = max(1, (int)$it['quantity']);
            $milk = trim((string)$it['milk']);
            foreach ($recipes_map[$pid] ?? [] as $rc) {
                $amount = $rc['amount_used'] * $qty;
                if ($amount <= 0) continue;
                if (strpos(strtolower(trim($rc['ingredient_name'])), 'milk') !== false) {
                    $key = strtolower(trim($milk !== '' ? $milk : 'Fresh Milk'));
                    if (isset($cost_map_ref[$key])) { $ocost += $amount * (float)$cost_map_ref[$key]['unit_cost']; }
                } else {
                    $ocost += $amount * (float)($cost_map_ref[$rc['ingredient_id']]['unit_cost'] ?? 0);
                }
            }
        }
        $cogsByOrder[$oid] = $ocost;
    }
}

$sum_gross  = 0.0;
$sum_disc   = 0.0;
$sum_net    = 0.0;
$sum_cogs   = 0.0;
$sum_profit = 0.0;
$sum_qty    = 0;

function fmtNum($val) {
    if ($val == 0) return '0';
    return ($val == floor($val) ? number_format($val, 0) : number_format($val, 2)) . '$';
}

$processed_rows = [];
$idx = 0;
foreach ($table_orders as $to) {
    $idx++;
    $dailyOrderNo = (int)($to['daily_order_no'] ?? $idx);
    $orderNoStr   = '#' . str_pad((string)$dailyOrderNo, 4, '0', STR_PAD_LEFT);
    $oid   = (int)$to['order_id'];
    $disc  = (float)($to['discount_amount'] ?? 0);
    $net   = (float)$to['total'];
    $gross = $net + $disc;
    $ocogs = (float)($cogsByOrder[$oid] ?? 0.0);
    $profit = $net - $ocogs;

    $o_its = $items_by_order[$oid] ?? [];
    $o_qty = 0;
    foreach ($o_its as $oit) {
        $o_qty += max(1, (int)($oit['quantity'] ?? 1));
    }

    $sum_gross  += $gross;
    $sum_disc   += $disc;
    $sum_net    += $net;
    $sum_cogs   += $ocogs;
    $sum_profit += $profit;
    $sum_qty    += $o_qty;

    $date_str = date('g:i j/n/Y', strtotime($to['order_date']));
    $raw_cust = trim($to['customer_name'] ?? '');
    if ($raw_cust === '' || strtolower($raw_cust) === 'general' || strtolower($raw_cust) === 'guest') {
        $cust = 'General';
    } else {
        $cust = htmlspecialchars($raw_cust);
    }
    $staff = htmlspecialchars($to['staff_name'] ?: 'Visal');

    $processed_rows[] = [
        'no'         => $orderNoStr,
        'date'       => $date_str,
        'customer'   => $cust,
        'price'      => fmtNum($gross),
        'qty_item'   => $o_qty,
        'total'      => fmtNum($net),
        'cogs'       => fmtNum($ocogs),
        'profit'     => fmtNum($profit),
        'currency'   => '$',
        'place_by'   => $staff,
    ];
}

$fmt_sum_gross  = fmtNum($sum_gross);
$fmt_sum_disc   = fmtNum($sum_disc);
$fmt_sum_net    = fmtNum($sum_net);
$fmt_sum_cogs   = fmtNum($sum_cogs);
$fmt_sum_profit = fmtNum($sum_profit);

$khr_rate = defined('KHR_RATE') ? (int)KHR_RATE : 4000;
$net_khr_val = round($sum_net * $khr_rate);
$fmt_sum_net_khr = $fmt_sum_net . ' = ' . number_format($net_khr_val) . '៛';

// DOMPDF mode check
if (!empty($_GET['dompdf'])) {
    $fontFamily = "'Hanuman', 'Kantumruy Pro', 'Noto Sans Khmer', 'Khmer OS Battambang', 'DejaVu Sans', sans-serif";
    ob_start(); ?>
    <!DOCTYPE html>
    <html>
    <head>
    <meta charset="UTF-8">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Hanuman:wght@400;700&family=Noto+Sans+Khmer:wght@400;700&display=swap" rel="stylesheet">
    <style>
      @import url('https://fonts.googleapis.com/css2?family=Hanuman:wght@400;700&family=Noto+Sans+Khmer:wght@400;700&display=swap');
      @page { margin: 25px 30px; }
      body { font-family: <?= $fontFamily ?>; font-size: 13px; color: #000; margin: 0; line-height: 1.5; }
      .report-header { margin-bottom: 22px; }
      .report-header h1 { font-size: 22px; font-weight: bold; margin: 0 0 5px 0; color: #000; }
      .report-header p { margin: 3px 0; font-size: 13px; color: #000; }
      .section-title { font-size: 13px; font-weight: bold; letter-spacing: 0.5px; margin-bottom: 12px; text-transform: uppercase; color: #000; }
      .report-table { width: 100%; border-collapse: collapse; margin-bottom: 22px; }
      .report-table th, .report-table td { border: 1px solid #000; padding: 6px 5px; text-align: center; font-size: 12px; font-family: <?= $fontFamily ?>; }
      .report-table th { background: #808080; color: #000; font-weight: bold; font-size: 12.5px; white-space: nowrap; }
      .report-table tr.total-row td { font-weight: bold; background: #c6efce; font-size: 12.5px; }
      .summary-footer { font-size: 14px; margin-top: 22px; color: #000; font-family: <?= $fontFamily ?>; line-height: 1.6; }
      .summary-footer p { margin: 0 0 10px 0; font-size: 14px; font-weight: normal; }
      .summary-footer .sum-item { margin: 4px 0; font-size: 14px; }
      .summary-footer .sum-item b.lbl { display: inline-block; width: 170px; font-weight: bold; }
    </style>
    </head>
    <body>
    <div class="report-header">
      <h1><?= he($lbl_cafe_title) ?></h1>
      <p><?= he($lbl_report_sale) ?></p>
      <p><?= he($lbl_period) ?> <?= he($filter_from) ?> <?= he($lbl_to) ?> <?= he($filter_to) ?></p>
      <p><?= he($lbl_generated) ?> <?= date('j/n/Y, g:i:s A') ?></p>
      <p><?= he($lbl_generated_by) ?> <?= he($gen_by_str) ?></p>
    </div>
    <div class="section-title"><?= he($lbl_table_title) ?></div>
    <table class="report-table">
      <thead>
        <tr>
          <th style="width:8%;"><?= he($lbl_col_no) ?></th>
          <th style="width:22%;"><?= he($lbl_col_date) ?></th>
          <th style="width:18%;"><?= he($lbl_col_cust) ?></th>
          <th style="width:12%;"><?= he($lbl_col_price) ?></th>
          <th style="width:10%;"><?= he($lbl_col_qty) ?></th>
          <th style="width:14%;"><?= he($lbl_col_total) ?></th>
          <th style="width:16%;"><?= he($lbl_col_place) ?></th>
        </tr>
      </thead>
      <tbody>
        <?php if (empty($processed_rows)): ?>
          <tr><td colspan="7" style="text-align:center; padding:14px"><?= $isKm ? 'គ្មានទិន្នន័យបញ្ជាទិញឡើយ' : 'No orders found for selected period.' ?></td></tr>
        <?php else: foreach ($processed_rows as $r): ?>
          <tr>
            <td><?= $r['no'] ?></td>
            <td><?= $r['date'] ?></td>
            <td><?= $r['customer'] ?></td>
            <td><?= $r['price'] ?></td>
            <td><?= $r['qty_item'] ?></td>
            <td><?= $r['total'] ?></td>
            <td><?= $r['place_by'] ?></td>
          </tr>
        <?php endforeach; ?>
          <tr class="total-row">
            <td colspan="3" style="text-align:center; background:#fff;"><?= he($lbl_col_sum) ?></td>
            <td style="background:#c6efce;"><?= $fmt_sum_gross ?></td>
            <td style="background:#c6efce;"><?= $sum_qty ?></td>
            <td style="background:#c6efce;"><?= $fmt_sum_net ?></td>
            <td style="background:#fff;"></td>
          </tr>
        <?php endif; ?>
      </tbody>
    </table>
    <div class="summary-footer">
      <p><?= he($lbl_date_from) ?> <?= he(date('j/n/Y', strtotime($filter_from))) ?> <?= he($lbl_date_to) ?> <?= he(date('j/n/Y', strtotime($filter_to))) ?></p>
      <div class="sum-item"><b class="lbl"><?= $isKm ? 'ការកម៉្មង់សរុប' : 'Total Order' ?></b> : <b><?= count($processed_rows) ?></b></div>
      <div class="sum-item"><b class="lbl"><?= he($lbl_gross_sales) ?></b> : <b><?= $fmt_sum_gross ?></b></div>
      <div class="sum-item"><b class="lbl"><?= he($lbl_total_items) ?></b> : <b><?= $sum_qty ?></b></div>
      <div class="sum-item"><b class="lbl"><?= he($lbl_net_revenue) ?></b> : <b><?= $fmt_sum_net_khr ?></b></div>
    </div>
    </body>
    </html>
    <?php
    $html = ob_get_clean();
    $options = new Options();
    $options->set('isRemoteEnabled', true);
    $options->set('defaultFont', 'Hanuman');
    $dompdf = new Dompdf($options);
    $dompdf->loadHtml($html, 'UTF-8');
    $dompdf->setPaper('A4', 'portrait');
    $dompdf->render();
    $dompdf->stream(($isRange ? 'sales-report-' . $dateFrom . '-' . $dateTo : 'daily-report-' . $date) . '.pdf', ['Attachment' => false]);
    exit;
}
?>
<!DOCTYPE html>
<html lang="<?= $isKm ? 'km' : 'en' ?>">
<head>
<meta charset="UTF-8">
<title><?= he($lbl_report_sale) ?> - <?= he($filter_from) ?> <?= he($lbl_to) ?> <?= he($filter_to) ?></title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Hanuman:wght@400;700&family=Kantumruy+Pro:wght@400;700&family=Noto+Sans+Khmer:wght@400;700&display=swap" rel="stylesheet">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Hanuman:wght@400;700&family=Kantumruy+Pro:wght@400;700&family=Noto+Sans+Khmer:wght@400;700&display=swap');

  @page { margin: 0; size: A4 portrait; }
  
  body {
    font-family: 'Hanuman', 'Kantumruy Pro', 'Noto Sans Khmer', 'Khmer OS Battambang', 'Khmer OS Siemreap', 'DejaVu Sans', 'Times New Roman', serif;
    font-size: 14px;
    color: #000000;
    margin: 0;
    padding: 20px;
    background: #ffffff;
    line-height: 1.55;
  }

  .no-print-bar {
    position: fixed;
    top: 0;
    left: 0;
    right: 0;
    background: #18181b;
    color: #ffffff;
    padding: 10px 24px;
    display: flex;
    align-items: center;
    justify-content: space-between;
    z-index: 9999;
    box-shadow: 0 4px 12px rgba(0,0,0,0.35);
    font-family: system-ui, -apple-system, sans-serif;
  }
  .no-print-bar .btn {
    background: #d1904b;
    color: #000;
    font-weight: 700;
    border: none;
    padding: 8px 18px;
    border-radius: 6px;
    cursor: pointer;
    font-size: 13px;
    text-decoration: none;
    display: inline-flex;
    align-items: center;
    gap: 6px;
  }
  .no-print-bar .btn-secondary {
    background: #3f3f46;
    color: #fff;
  }

  * {
    -webkit-print-color-adjust: exact !important;
    print-color-adjust: exact !important;
  }

  @media print {
    * {
      -webkit-print-color-adjust: exact !important;
      print-color-adjust: exact !important;
    }
    .no-print-bar { display: none !important; }
    body { padding: 15mm 20mm !important; margin: 0 !important; }
    .report-wrapper { margin: 0 auto; max-width: 100%; }
    .report-table th {
      background-color: #808080 !important;
      -webkit-print-color-adjust: exact !important;
      print-color-adjust: exact !important;
    }
    .report-table tr.total-row td {
      -webkit-print-color-adjust: exact !important;
      print-color-adjust: exact !important;
    }
  }

  .report-wrapper {
    max-width: 820px;
    margin: 50px auto 0;
  }

  .report-header { margin-bottom: 22px; }
  .report-header h1 { font-size: 24px; font-weight: bold; margin: 0 0 5px 0; color: #000; }
  .report-header p { margin: 3px 0; font-size: 14px; color: #000; }
  .section-title { font-size: 14px; font-weight: bold; letter-spacing: 0.5px; margin-bottom: 12px; text-transform: uppercase; color: #000; }
  .report-table { width: 100%; border-collapse: collapse; margin-bottom: 22px; }
  .report-table th, .report-table td { border: 1px solid #000; padding: 6px 5px; text-align: center; font-size: 13px; }
  .report-table th {
    background-color: #808080 !important;
    color: #000 !important;
    font-weight: bold;
    font-size: 13.5px;
    white-space: nowrap;
    -webkit-print-color-adjust: exact !important;
    print-color-adjust: exact !important;
  }
  .report-table tr.total-row td { font-weight: bold; font-size: 13.5px; }

  .summary-footer { font-size: 14px; margin-top: 22px; color: #000; line-height: 1.6; }
  .summary-footer p { margin: 0 0 10px 0; font-size: 14px; font-weight: normal; }
  .summary-footer .sum-item { margin: 5px 0; font-size: 15px; }
  .summary-footer .sum-item b.lbl { display: inline-block; min-width: 170px; font-weight: bold; }
</style>
</head>
<body>

<div class="no-print-bar">
  <div style="font-size:14px; font-weight:600;">
    <?= $isKm ? 'មើលរបាយការណ៍បោះពុម្ព (Print Preview)' : 'Report Print Preview' ?>
  </div>
  <div style="display:flex; gap:10px;">
    <button class="btn" onclick="window.print()">
      🖨️ <?= $isKm ? 'បោះពុម្ពឥឡូវនេះ (Print Now)' : 'Print Now' ?>
    </button>
    <a href="<?= htmlspecialchars($_SERVER['REQUEST_URI']) ?>&dompdf=1" class="btn btn-secondary">
      📄 <?= $isKm ? 'ទាញយក PDF (Download PDF)' : 'Download PDF' ?>
    </a>
  </div>
</div>

<div class="report-wrapper">
  <div class="report-header">
    <h1><?= he($lbl_cafe_title) ?></h1>
    <p><?= he($lbl_report_sale) ?></p>
    <p><?= he($lbl_period) ?> <?= he($filter_from) ?> <?= he($lbl_to) ?> <?= he($filter_to) ?></p>
    <p><?= he($lbl_generated) ?> <?= date('j/n/Y, g:i:s A') ?></p>
    <p><?= he($lbl_generated_by) ?> <?= he($gen_by_str) ?></p>
  </div>

  <div class="section-title"><?= he($lbl_table_title) ?></div>

  <table class="report-table">
    <thead>
      <tr>
        <th style="width:8%;"><?= he($lbl_col_no) ?></th>
        <th style="width:22%;"><?= he($lbl_col_date) ?></th>
        <th style="width:18%;"><?= he($lbl_col_cust) ?></th>
        <th style="width:12%;"><?= he($lbl_col_price) ?></th>
        <th style="width:10%;"><?= he($lbl_col_qty) ?></th>
        <th style="width:14%;"><?= he($lbl_col_total) ?></th>
        <th style="width:16%;"><?= he($lbl_col_place) ?></th>
      </tr>
    </thead>
    <tbody>
      <?php if (empty($processed_rows)): ?>
        <tr><td colspan="7" style="text-align:center; padding:14px"><?= $isKm ? 'គ្មានទិន្នន័យបញ្ជាទិញឡើយ' : 'No orders found for selected period.' ?></td></tr>
      <?php else: foreach ($processed_rows as $r): ?>
        <tr>
          <td><?= $r['no'] ?></td>
          <td><?= $r['date'] ?></td>
          <td><?= $r['customer'] ?></td>
          <td><?= $r['price'] ?></td>
          <td><?= $r['qty_item'] ?></td>
          <td><?= $r['total'] ?></td>
          <td><?= $r['place_by'] ?></td>
        </tr>
      <?php endforeach; ?>
        <tr class="total-row">
          <td colspan="3" style="text-align:center; background:#fff;"><?= he($lbl_col_sum) ?></td>
          <td style="background:#c6efce;"><?= $fmt_sum_gross ?></td>
          <td style="background:#c6efce;"><?= $sum_qty ?></td>
          <td style="background:#c6efce;"><?= $fmt_sum_net ?></td>
          <td style="background:#fff;"></td>
        </tr>
      <?php endif; ?>
    </tbody>
  </table>

  <div class="summary-footer">
    <p><?= he($lbl_date_from) ?> <?= he(date('j/n/Y', strtotime($filter_from))) ?> <?= he($lbl_date_to) ?> <?= he(date('j/n/Y', strtotime($filter_to))) ?></p>
    <div class="sum-item"><b class="lbl"><?= $isKm ? 'ការកម៉្មង់សរុប' : 'Total Order' ?></b> : <b><?= count($processed_rows) ?></b></div>
    <div class="sum-item"><b class="lbl"><?= he($lbl_gross_sales) ?></b> : <b><?= $fmt_sum_gross ?></b></div>
    <div class="sum-item"><b class="lbl"><?= he($lbl_total_items) ?></b> : <b><?= $sum_qty ?></b></div>
    <div class="sum-item"><b class="lbl"><?= he($lbl_net_revenue) ?></b> : <b><?= $fmt_sum_net_khr ?></b></div>
  </div>
</div>

<script>
window.addEventListener('DOMContentLoaded', () => {
  // Automatically trigger print dialog when page finishes loading
  setTimeout(() => { window.print(); }, 400);
});
</script>
</body>
</html>
