<?php
/**
 * Printable Employee Report layout.
 * Supports print dialog and matches exact report layout.
 */
require 'auth.php';
require 'config.php';
require_once 'lang.php';

if (!can('report') && !can('report_employee')) { 
    header("Location: dashboard.php?denied=1"); 
    exit; 
}

date_default_timezone_set('Asia/Phnom_Penh');

function he($s) { return htmlspecialchars((string)$s, ENT_QUOTES, 'UTF-8'); }

// Language & Labels
$lang = is_string($_GET['lang'] ?? null) ? trim($_GET['lang']) : current_lang();
$isKm = ($lang === 'km');

$lbl_cafe_title   = 'The Bird Nest Café';
$lbl_report_title = $isKm ? 'របាយការណ៍បុគ្គលិក' : 'Report Employe';
$lbl_period       = $isKm ? 'រយៈពេល:' : 'Period:';
$lbl_to           = $isKm ? 'ដល់' : 'to';
$lbl_generated    = $isKm ? 'បង្កើតនៅ:' : 'Generated:';
$lbl_generated_by = $isKm ? 'បង្កើតដោយ:' : 'Generated by:';
$lbl_table_title  = $isKm ? 'តារាងរបាយការណ៍បុគ្គលិក' : 'EMPLOYE REPORT TABLE';

$lbl_staff_id     = $isKm ? 'អត្តលេខ' : 'Staff ID';
$lbl_emp_name     = $isKm ? 'ឈ្មោះបុគ្គលិក' : 'Employee Name';
$lbl_role         = $isKm ? 'តួនាទី' : 'Role';
$lbl_total_orders = $isKm ? 'ការកម៉្មង់សរុប' : 'Total Orders';
$lbl_revenue      = $isKm ? 'ចំណូលសរុប' : 'Billed Revenue';
$lbl_total        = $isKm ? 'សរុប' : 'Total';

// Date range calculation
$today = date('Y-m-d');
$filter_from = trim($_GET['date_from'] ?? $_GET['from_date'] ?? $_GET['from'] ?? $today);
$filter_to   = trim($_GET['date_to']   ?? $_GET['to_date']   ?? $_GET['to']   ?? $today);
if (!preg_match('/^\d{4}-\d{2}-\d{2}$/', $filter_from)) $filter_from = $today;
if (!preg_match('/^\d{4}-\d{2}-\d{2}$/', $filter_to))   $filter_to   = $today;
if ($filter_from > $filter_to) [$filter_from, $filter_to] = [$filter_to, $filter_from];

$_is_mgr = in_array($_SESSION['role'] ?? '', ['admin', 'manager']);
$filter_user = (int)($_GET['user_id'] ?? $_GET['user'] ?? 0);
if (!$_is_mgr) {
    $filter_user = (int)$_SESSION['user_id'];
}

$where_cond = ["DATE(o.order_date) BETWEEN '$filter_from' AND '$filter_to'"];
if ($filter_user > 0) {
    $where_cond[] = "(o.user_id = $filter_user OR o.employee_id = $filter_user)";
}
$where_str = implode(' AND ', $where_cond);

$where_user = $filter_user > 0 ? "WHERE u.user_id = $filter_user" : "";

$sql_staff = "SELECT 
                u.user_id,
                u.username,
                e.name AS emp_name,
                r.slug AS role,
                COUNT(o.order_id) AS total_orders,
                COALESCE(SUM(CASE WHEN o.status NOT IN ('Cancelled','Refunded') THEN o.total ELSE 0 END), 0) AS total_sales
              FROM users u
              LEFT JOIN employees e ON e.user_id = u.user_id
              LEFT JOIN roles r ON r.id = u.role_id
              LEFT JOIN orders o ON o.user_id = u.user_id AND $where_str
              $where_user
              GROUP BY u.user_id, u.username, e.name, r.slug
              ORDER BY total_sales DESC";
$res_staff = $conn->query($sql_staff);
$staff_rows = $res_staff ? $res_staff->fetch_all(MYSQLI_ASSOC) : [];

$grand_total_orders = 0;
$grand_total_sales  = 0.0;
foreach ($staff_rows as $sr) {
    $grand_total_orders += (int)$sr['total_orders'];
    $grand_total_sales  += (float)$sr['total_sales'];
}

$_gen_role = ucfirst($_SESSION['role'] ?? 'Admin');
$_gen_name = $_SESSION['emp_name'] ?? $_SESSION['username'] ?? 'Admin';
$gen_by_str = (strtolower($_gen_role) !== strtolower($_gen_name)) ? "{$_gen_role} ({$_gen_name})" : $_gen_name;
$gen_time = date('n/j/Y, g:i:s A');
?>
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Report Employe | The Bird Nest Café</title>
<style>
  * {
    -webkit-print-color-adjust: exact !important;
    print-color-adjust: exact !important;
  }
  body {
    font-family: "Times New Roman", Times, Georgia, serif;
    background: #fff;
    color: #000;
    margin: 40px;
    padding: 0;
    font-size: 14px;
    line-height: 1.45;
    -webkit-print-color-adjust: exact !important;
    print-color-adjust: exact !important;
  }
  .print-container {
    max-width: 800px;
    margin: 0 auto;
  }
  .header-section {
    margin-bottom: 25px;
  }
  .header-section h1 {
    font-size: 24px;
    font-weight: normal;
    margin: 0 0 10px 0;
  }
  .header-section p {
    margin: 3px 0;
    font-size: 13px;
  }
  .section-title {
    font-size: 13px;
    font-weight: bold;
    letter-spacing: 0.5px;
    margin: 25px 0 10px 0;
  }
  table.report-table {
    width: 100%;
    border-collapse: collapse;
    margin-bottom: 25px;
    font-size: 13px;
  }
  table.report-table th, table.report-table td {
    border: 1px solid #000;
    padding: 6px 12px;
    text-align: center;
  }
  table.report-table th {
    background-color: #808080 !important;
    color: #000 !important;
    font-weight: bold;
    -webkit-print-color-adjust: exact !important;
    print-color-adjust: exact !important;
  }
  table.report-table tr.total-row td {
    background-color: #86d97c !important;
    font-weight: bold;
    -webkit-print-color-adjust: exact !important;
    print-color-adjust: exact !important;
  }
  .summary-section {
    font-size: 14px;
    margin-top: 15px;
  }
  .summary-section p {
    margin: 6px 0;
  }
  @page {
    margin: 0;
  }
  @media print {
    @page {
      margin: 0;
    }
    * {
      -webkit-print-color-adjust: exact !important;
      print-color-adjust: exact !important;
    }
    body {
      margin: 0 !important;
      padding: 15mm 20mm !important;
    }
    table.report-table th {
      background-color: #808080 !important;
      -webkit-print-color-adjust: exact !important;
      print-color-adjust: exact !important;
    }
    table.report-table tr.total-row td {
      background-color: #86d97c !important;
      -webkit-print-color-adjust: exact !important;
      print-color-adjust: exact !important;
    }
  }
</style>
</head>
<body>
<div class="print-container">
  <div class="header-section">
    <h1><?= he($lbl_cafe_title) ?></h1>
    <p><?= he($lbl_report_title) ?></p>
    <p><?= he($lbl_period) ?> <?= he($filter_from) ?> <?= he($lbl_to) ?> <?= he($filter_to) ?></p>
    <p><?= he($lbl_generated) ?> <?= he($gen_time) ?></p>
    <p><?= he($lbl_generated_by) ?> <?= he($gen_by_str) ?></p>
  </div>

  <div class="section-title"><?= he($lbl_table_title) ?></div>

  <table class="report-table">
    <thead>
      <tr>
        <th><?= he($lbl_staff_id) ?></th>
        <th><?= he($lbl_emp_name) ?></th>
        <th><?= he($lbl_role) ?></th>
        <th><?= he($lbl_total_orders) ?></th>
        <th><?= he($lbl_revenue) ?></th>
      </tr>
    </thead>
    <tbody>
      <?php if (empty($staff_rows)): ?>
        <tr><td colspan="5" style="padding:15px;"><?= $isKm ? 'គ្មានទិន្នន័យ' : 'No data' ?></td></tr>
      <?php else: foreach ($staff_rows as $s): ?>
        <?php 
          $empName = !empty($s['emp_name']) ? $s['emp_name'] : $s['username'];
          $roleStr = ucfirst($s['role'] ?? 'Cashier');
          $val     = (float)$s['total_sales'];
          $valFmt  = (floor($val) == $val) ? number_format($val, 0) : number_format($val, 2);
        ?>
        <tr>
          <td>#STF-<?= (int)$s['user_id'] ?></td>
          <td><?= he($empName) ?></td>
          <td><?= he($roleStr) ?></td>
          <td><?= (int)$s['total_orders'] ?></td>
          <td><?= $valFmt ?>$</td>
        </tr>
      <?php endforeach; ?>
        <?php 
          $totFmt = (floor($grand_total_sales) == $grand_total_sales) ? number_format($grand_total_sales, 0) : number_format($grand_total_sales, 2);
        ?>
        <tr class="total-row">
          <td colspan="3"><?= he($lbl_total) ?></td>
          <td><?= $grand_total_orders ?></td>
          <td><?= $totFmt ?>$</td>
        </tr>
      <?php endif; ?>
    </tbody>
  </table>

  <div class="summary-section">
    <p>Date From: <?= date('n/j/Y', strtotime($filter_from)) ?> Date to <?= date('n/j/Y', strtotime($filter_to)) ?></p>
    <p>Total Order &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: <strong><?= $grand_total_orders ?></strong></p>
    <p>Billed Revenue : <strong><?= (floor($grand_total_sales) == $grand_total_sales) ? number_format($grand_total_sales, 0) : number_format($grand_total_sales, 2) ?>$</strong></p>
  </div>
</div>

<script>
window.addEventListener('DOMContentLoaded', () => {
  setTimeout(() => { window.print(); }, 400);
});
</script>
</body>
</html>
