<?php
// Multi-language translation helper for Bird's Nest Coffee Application
if (session_status() === PHP_SESSION_NONE) {
    session_start();
}

// Detect language setting (Session -> Cookie -> Default 'en')
if (!isset($_SESSION['lang'])) {
    $_SESSION['lang'] = $_COOKIE['lang'] ?? 'en';
}

$_current_lang = in_array($_SESSION['lang'], ['en', 'km'], true) ? $_SESSION['lang'] : 'en';

$_translations = [
    'en' => [
        // Brand & Theme
        'brand_name' => "Bird's Nest",
        'dark_mode' => 'Dark',
        'light_mode' => 'Light',
        'clock_in' => 'Clock In',
        'clock_out' => 'Clock Out',
        'logout' => 'Logout',
        'good_morning' => 'Good morning',
        'good_afternoon' => 'Good afternoon',
        'good_evening' => 'Good evening',
        'english' => 'English',
        'khmer' => 'Khmer (ខ្មែរ)',
        'language' => 'Language',

        // Navigation
        'nav_dashboard' => 'Dashboard',
        'nav_take_order' => 'Take Order',
        'nav_orders' => 'Orders',
        'nav_products' => 'Products',
        'nav_categories' => 'Categories',
        'nav_stock' => 'Stock & Inventory',
        'nav_stock_drinks' => 'Stock Drink',
        'nav_raw_ingredients' => 'Ingredient',
        'nav_ingredients' => 'Ingredient',
        'nav_report' => 'Report',
        'nav_employees' => 'Employees',
        'nav_users' => 'Users',
        'nav_manage_roles' => 'Manage Roles',
        'nav_user_management' => 'User Management',
        'nav_settings' => 'Settings',
        'nav_my_profile' => 'My Profile',
        'nav_stock_count' => 'Stock Count',
        'nav_suppliers' => 'Suppliers',
        'nav_purchase_orders' => 'Purchase Orders',
        'nav_recipes' => 'Recipes & BOM',
        'no_recipe' => 'No Recipe',
        'nav_loyalty' => 'Loyalty Rewards',
        'nav_announcements' => 'Announcements',
        'nav_barista_display' => 'Barista Station',
        'nav_customer_display' => 'Customer Display',

        // Report Submenu
        'nav_reports' => 'Reports',
        'nav_daily_report' => 'Daily Summary',
        'nav_sales_report' => 'Analytics & Export',
        'nav_shift_report' => 'Shift Audit',
        'nav_report_sale' => 'Report Sale',
        'nav_report_product' => 'Report Product',
        'nav_inventory_report' => 'Report Ingredient',
        'nav_employee_report' => 'Report User',

        // Sections
        'sec_orders' => 'Orders',
        'sec_operations' => 'Operations',
        'sec_inventory' => 'Inventory',
        'sec_procurement' => 'Procurement',
        'sec_reconciliation' => 'Reconciliation',
        'sec_loyalty' => 'Loyalty',
        'sec_analytics' => 'Analytics',
        'sec_staff' => 'Staff',
        'sec_admin' => 'Admin',
        'sec_account' => 'Account',

        // KPIs
        'revenue_today' => 'Revenue Today',
        'profit_today' => 'Profit Today',
        'orders_today' => 'Orders Today',
        'items_sold' => 'Items Sold',
        'vs_yesterday' => 'vs yesterday',
        'no_data_yesterday' => 'No data yesterday',
        'no_sales_today' => 'No sales yet today',
        'margin' => 'margin',
        'completed' => 'completed',
        'from_completed_orders' => 'from completed orders',
        'view_report' => 'View report',
        'view_breakdown' => 'View breakdown',
        'view_orders' => 'View orders',
        'view_items' => 'View items',

        // Dashboard Charts
        'profit_loss' => 'Profit & Loss',
        'net_profit_today' => 'NET PROFIT TODAY',
        'revenue_income' => 'REVENUE / INCOME',
        'cogs_ingredient_cost' => 'COGS / INGREDIENT COST',
        'margin_rate' => 'Margin Rate',
        'gross_margin' => 'Gross Profit',
        'category_sales' => 'Category Sales',
        'hourly_orders' => 'Hourly Orders',
        'sales_trend' => 'Sales Trend',
        'today' => 'Today',
        'last_7_days' => 'Last 7 Days',
        'distribution' => 'Distribution',
        'orders' => 'Orders',
        'profit' => 'Profit',
        'revenue' => 'Revenue',

        // POS / Menu
        'search_products' => 'Search drinks...',
        'all_categories' => 'All Categories',
        'top_sellers' => 'Top Sellers',
        'seller_num_1' => '#1 Seller',
        'top_pick' => 'Top Pick',
        'best_seller' => 'Best Seller',
        'cart' => 'Cart',
        'cart_empty' => 'Cart is empty',
        'tap_drink_to_add' => 'Tap a drink to add it',
        'subtotal' => 'Subtotal',
        'tax' => 'Tax',
        'total' => 'Total',
        'order_type' => 'Order Type',
        'place_order' => 'Place Order',
        'confirm_order' => 'Confirm Order',
        'add_to_order' => 'Add to Order #',
        'add_to_cart' => 'Add to Cart',
        'checkout' => 'Checkout',
        'clear_cart' => 'Clear Cart',
        'customer_name' => 'Customer Name',
        'dine_in' => 'Drink In',
        'takeaway' => 'Drink Out',
        'payment_method' => 'Payment Method',
        'cash' => 'Cash',
        'bakong_khqr' => 'Bakong',
        'pay_later' => 'Pay Later',

        // Customization Modal
        'sweetness' => 'Sugar',
        'ice' => 'Ice',
        'no_ice' => 'No Ice',
        'less_ice' => 'Less Ice',
        'normal_ice' => 'Normal Ice',
        'more_ice' => 'More Ice',

        // Orders Board / View Orders
        'all_orders' => 'All Order',
        'show_all_orders' => 'Show all orders',
        'new_order' => 'New Order',
        'in_prep_queue' => 'In preparation queue',
        'making' => 'Making',
        'being_prepared' => 'Being prepared',
        'complete_order' => 'Complete Order',
        'finished_today' => 'Finished today',
        'overdue_order' => 'Overdue Order',
        'over_10_mins' => 'Over 10 mins in queue',
        'total_price' => 'Total Price',
        'total_sales_today' => 'Total sales today',
        'search_orders_ph' => 'Search by customer name, order #, or status...',
        'clear' => 'Clear',
        'col_no' => 'No.',
        'col_item' => 'ITEM',
        'col_total_price' => 'Total Price',
        'col_time' => 'DATE & TIME',
        'col_status' => 'Status',
        'col_place_by' => 'Place By',
        'col_action' => 'Action',
        'view_detail' => 'View Detail',
        'reprint' => 'Reprint',
        'range_all' => 'All Time',
        'range_today' => 'Today',
        'range_this_week' => 'This Week',
        'range_this_month' => 'This Month',
        'range_this_year' => 'This Year',
        'item_single' => 'item',
        'item_plural' => 'items',
        'no_orders_found' => 'No orders found',
        'try_changing_search' => 'Try changing search query or header filter card.',

        // Orders List Statuses
        'order_id' => 'Order #',
        'customer' => 'Customer',
        'date_time' => 'Date & Time',
        'status' => 'Status',
        'actions' => 'Actions',
        'status_paid' => 'Paid',
        'status_pending' => 'Pending',
        'status_preparing' => 'Preparing',
        'status_completed' => 'Completed',
        'status_cancelled' => 'Cancelled',
        'status_refunded' => 'Refunded',

        // Products & Categories
        'manage_categories' => 'Manage Categories',
        'catalog' => 'Catalog',
        'active' => 'Active',
        'inactive' => 'Inactive',
        'visible_on_menu' => 'Visible on menu',
        'hidden_from_menu' => 'Hidden from menu',
        'offers' => 'Offers',
        'sweet' => 'Sweet',
        'milk' => 'Milk',
        'add_ons' => 'Add-ons',
        'on' => 'On',
        'off' => 'Off',
        'add_product' => 'Add Product',
        'edit_product' => 'Edit Product',
        'product_name' => 'Product Name',
        'category' => 'Category',
        'price' => 'Price',
        'cost' => 'Cost',
        'image' => 'Image',
        'in_stock' => 'In Stock',
        'out_of_stock' => 'Out of Stock',
        'add_category' => 'Add Category',
        'category_name' => 'Category Name',
        'top_category' => 'Top Category',
        'products_on_menu' => 'products on menu',
        'off_menu' => 'items off menu',
        'search_products_ph' => 'Search products… (Press /)',

        // Ingredients & Inventory
        'btn_history' => 'History',
        'btn_export_pdf' => 'Export PDF',
        'add_ingredient' => 'Add Ingredient',
        'ingredient_name' => 'Ingredient Name',
        'stock_level' => 'Stock Level',
        'unit' => 'Unit',
        'min_stock' => 'Reorder Level',
        'low_stock' => 'Low Stock',
        'available' => 'Available',
        'below_minimum' => 'Below minimum',
        'needs_restock' => 'Needs restock',
        'stock_value' => 'Stock Value',
        'total_investment' => 'Total investment',
        'search_ingredients_ph' => 'Search ingredients… (Press /)',
        'cost_per_unit' => 'Cost Per Unit',

        // Employees & Users & Roles
        'total_staff' => 'Total Staff',
        'employees_on_record' => 'Employees on record',
        'orders_this_month' => 'Orders This Month',
        'all_time' => 'all-time',
        'top_this_month' => 'Top This Month',
        'no_data_yet' => 'No data yet',
        'revenue_served' => 'Revenue Served',
        'all_time_all_staff' => 'All-time, all staff',
        'all_time_orders' => 'All-Time Orders',
        'by_all_staff' => 'By all staff',
        'search_emp_ph' => 'Search by name or job title…',
        'all_roles' => 'All Roles',
        'add_new_employee' => 'Add New Employee',
        'col_staff_id' => 'Staff ID',
        'col_name' => 'Name',
        'col_role' => 'Role',
        'col_phone' => 'Phone',
        'col_shift' => 'Shift',
        'shift_morning' => 'Morning',
        'shift_afternoon' => 'Afternoon',
        'shift_night' => 'Night',

        'users_management' => 'Users Management',
        'users_management_sub' => 'Manage system users, administrator accounts and access privileges',
        'search_user_ph' => 'Search user...',
        'add_new_user' => 'Add New User',
        'col_user' => 'User',
        'col_emp_name' => 'Employee Name',
        'col_password' => 'Password',
        'btn_change' => 'Change',
        'badge_you' => 'You',

        'manage_role_permissions' => 'Manage Role Permissions',
        'admin_only' => 'Admin Only',
        'manage_role_sub' => 'Control which pages and features each role can access. Admin always retains full access.',
        'roles' => 'Roles',
        'permissions' => 'Permissions',
        'modules' => 'Modules',
        'user_overrides' => 'User Overrides',
        'create_role' => 'Create Role',
        'roles_overview' => 'Roles Overview',
        'staff' => 'staff',

        'add_employee' => 'Add Employee',
        'add_user' => 'Add User',
        'full_name' => 'Full Name',
        'role' => 'Role',
        'username' => 'Username',
        'phone' => 'Phone Number',
        'created_at' => 'Created Date',
        'role_name' => 'Role Name',

        // Reports
        'daily_sales_report' => 'Daily Sales Report',
        'product_sales_report' => 'Product Sales Report',
        'inventory_report' => 'Inventory Report',
        'shift_report' => 'Shift Report',
        'date' => 'Date',
        'total_revenue' => 'Total Revenue',
        'total_profit' => 'Total Profit',

        // Common Buttons & Messages
        'search' => 'Search',
        'save' => 'Save',
        // Inventory & Direct Drinks Stock
        'direct_drinks_stock' => 'Stock Drink',
        'cans_and_bottles' => 'Cans & Bottles',
        'raw_ingredients_supplies' => 'Raw Ingredients & Supplies',
        'recipe_bom' => 'Recipe BOM',
        'audit_and_logs' => 'Audit & Logs',
        'add_canned_bottled_drink' => 'Add Canned / Bottled Drink',
        'add_raw_ingredient' => 'Add Raw Ingredient',
        'add_ingredient' => 'Add New Ingredient',
        'quick_restock' => 'Quick Restock',
        'log_waste' => 'Log Waste / Spillage',
        'kpi_total' => 'TOTAL',
        'kpi_in_stock' => 'IN STOCK',
        'kpi_low_stock' => 'LOW STOCK',
        'kpi_out_of_stock' => 'OUT OF STOCK',
        'kpi_valuation' => 'VALUATION',
        'healthy_stock' => 'healthy stock',
        'reorder_soon' => 'reorder soon',
        'depleted_items' => 'depleted items',
        'direct_drinks' => 'Direct drinks',
        'raw_materials' => 'Raw materials',
        'products_unit' => 'Products',
        'ingredients_unit' => 'Ingredients',
        'search_drinks_ph' => 'Search direct drinks by name (e.g. Sting, Coke, Water)...',
        'search_ingredients_ph' => 'Search ingredients by name, category, notes...',
        'all_categories' => 'All Categories',
        'all_ingredient_categories' => 'All Ingredient Categories',
        'sort_name_asc' => 'Name: A to Z',
        'sort_name_desc' => 'Name: Z to A',
        'sort_qty_asc' => 'Qty: Low to High',
        'sort_qty_desc' => 'Qty: High to Low',
        'sort_val_desc' => 'Highest Valuation',
        'sort_newest' => 'Recently Added',
        'col_drink_product' => 'Drink Product',
        'col_ingredient_details' => 'Ingredient Details',
        'col_ingredient' => 'Ingredient',
        'col_category' => 'Category',
        'col_unit' => 'Unit',
        'col_conversion_rate' => 'Conversion Rate',
        'col_total_qty' => 'Total Qty (Units)',
        'col_on_hand_qty' => 'Qty on Hand',
        'col_qty_on_hand' => 'Qty on Hand',
        'col_alert_threshold' => 'Alert Threshold',
        'col_estimated_capacity' => 'Estimated Capacity',
        'col_breakdown' => 'Package Breakdown',
        'col_cost_box_unit' => 'Cost (Per Box / Unit)',
        'col_sell_price_unit' => 'Sell Price / Unit',
        'col_sell_price_box' => 'Sell Price / Box',
        'col_cost_unit' => 'Cost Per Unit ($)',
        'col_cost_box' => 'Cost Per Box ($)',
        'cost_price_unit' => 'Cost Price Per Unit ($)',
        'cost_price_box' => 'Cost Price Per Box ($)',
        'sell_price_unit' => 'Sell Price Per Unit ($)',
        'sell_price_box' => 'Sell Price Per Box ($)',
        'single_unit' => 'Single Unit',
        'package_unit' => 'Package Unit',
        'units_per_package' => 'Units Per Package',
        'initial_boxes' => 'Initial Boxes',
        'loose_units' => 'Loose Units',
        'alert_threshold' => 'Alert Threshold',
        'col_status' => 'Status',
        'col_valuation' => 'Valuation',
        'col_actions' => 'Actions',
        'cat_dairy' => 'Dairy & Milk',
        'cat_beans' => 'Coffee Beans',
        'cat_syrups' => 'Syrups & Flavors',
        'cat_packaging' => 'Cups & Packaging',
        'cat_bakery' => 'Bakery / Toppings',
        'cat_general' => 'General Supplies',
        'status_in_stock' => 'In Stock',
        'status_low_stock' => 'Low Stock',
        'status_out_of_stock' => 'Out of Stock',
        'btn_restock' => 'Restock',
        'btn_edit' => 'Edit',
        'btn_delete' => 'Delete',
        'btn_close' => 'Close',
        'btn_cancel' => 'Cancel',
        'btn_confirm_restock' => 'Confirm Restock',
        'btn_update_drink' => 'Update Drink',
        'btn_update_ingredient' => 'Update Ingredient',
        'showing_drinks_count' => 'Showing direct drinks',
        'showing_ingredients_count' => 'Showing ingredients',
        'quantity_added' => 'Quantity to Add',
        'quantity_wasted' => 'Quantity Wasted',
        'notes' => 'Notes',
        'date' => 'Date',
        'loose' => 'loose',
        'full' => 'full',
        'box' => 'box',
        'boxes' => 'boxes',
        'can' => 'can',
        'cans' => 'cans',
        'bottle' => 'bottle',
        'bottles' => 'bottles',
        'audit_ledger_title' => 'Direct Drinks Audit & History Ledger',
        'audit_ledger_sub' => 'Recent box restocks and direct drink activity history.',
        'recent_restocks' => 'Recent Box Restocks',
        'recent_deductions' => 'Stock Out / Deduction History',
        'recent_waste' => 'Recent Wastage / Breakage',
        'tab_restocks' => 'Restock History',
        'tab_deduct' => 'Deduct History',
        'tab_waste' => 'Waste History',
        'recent_restocks' => 'Recent Restocks',
        'recent_deductions' => 'Recent Stock Deductions',
        'boxes_added' => 'Boxes Added',
        'loose_added' => 'Loose Units',
        'total_units_added' => 'Total Units',
        'boxes_deducted' => 'Boxes Out',
        'loose_deducted' => 'Loose Out',
        'total_deducted' => 'Total Out',
        'units_added' => 'Units Added',
        'supplier_notes' => 'Supplier / Notes',
        'order_notes' => 'Order / Deduction Notes',
        'staff_member' => 'Staff',
        'reason' => 'Reason',
        'no_restocks_yet' => 'No restock entries recorded yet.',
        'no_deduct_yet' => 'No stock deduction entries recorded yet.',
        'no_waste_yet' => 'No waste logged yet.',
        'filter_date_time' => 'Filter by Date & Time',
        'filter_all' => 'All',
        'filter_today' => 'Today',
        'filter_yesterday' => 'Yesterday',
        'filter_this_week' => 'This Week',
        'filter_this_month' => 'This Month',
        'from_date' => 'From Date',
        'to_date' => 'To Date',
        'search_drink_order' => 'Search drink, order #, staff...',
        'clear_filter' => 'Clear',
        'no_match_filter' => 'No records match the selected date/filter criteria.',

        // Cash Settlement Modal
        'cpm_modal_title' => 'Cash Payment Settlement',
        'cpm_modal_subtitle' => 'Take order cash & calculate change',
        'cpm_summary_title' => 'Current Transaction Summary',
        'cpm_col_items' => 'Items',
        'cpm_col_price' => 'Price',
        'cpm_col_qty' => 'Qty',
        'cpm_col_total' => 'Total',
        'cpm_subtotal' => 'Running Subtotal',
        'cpm_discount' => 'Discount',
        'cpm_tax' => 'Tax',
        'cpm_total_due' => 'Total Amount Due',
        'cpm_payment_details' => 'Payment Details',
        'cpm_amount_received' => 'Amount Received',
        'cpm_quick_cash' => 'Quick Cash',
        'cpm_exact' => 'Exact',
        'cpm_payment_method' => 'Payment Method',
        'cpm_method_cash' => 'Cash',
        'cpm_method_bakong' => 'Bakong QR',
        'cpm_keypad' => 'Keypad',
        'cpm_change_calc' => 'Change Calculated',
        'cpm_return_method' => 'Return Method',
        'cpm_return_change_in' => 'Return Change In',
        'cpm_mode_mixed' => 'Dollar + Riel',
        'cpm_mode_usd' => 'Dollar',
        'cpm_mode_khr' => 'Riel',
        'cpm_change_to_return' => 'Change to Return',
        'cpm_cancel' => 'Cancel',
        'cpm_apply_payment' => 'Apply Payment & Print Receipt',
        'cpm_apply_bakong' => 'Apply Payment & Show QR',
        'cpm_cancel_order' => 'Cancel Order',
        'cpm_confirm_received' => 'Confirm Payment Received',
        'cpm_payment_received' => 'Payment Received!',
        'cpm_order_settled_bakong' => 'Order has been settled via Bakong KHQR.',
        'cpm_auto_completing' => 'Auto-completing in',
        'cpm_waiting_bakong' => 'Waiting for Bakong payment...',
        'cpm_khqr_scan_pay' => 'KHQR SCAN TO PAY',
        'cpm_under_10_riel' => 'Under $10: Return in Riel notes only',
        'cpm_exact_amount' => 'Exact Amount',
        'cpm_need_more' => 'Need more',
        'cpm_bakong_no_change_label' => 'KHQR Transfer',
        'cpm_exact_no_change' => 'Exact Amount • No Change Needed',
        'cpm_digital_payment_title' => 'Digital Transfer (No Change Required)',
        'cpm_exact_khqr_total' => 'Exact KHQR Total',

        // Cart Item Removal Alert
        'cart_remove_item_title' => 'Remove Item from Cart?',
        'cart_remove_item_msg' => 'Are you sure you want to remove ":item" from the cart?',
        'cart_remove_item_confirm' => 'Yes, Remove',
        'cart_clear_title' => 'Clear All Items?',
        'cart_clear_msg' => 'Are you sure you want to remove all items from the cart?',
        'cart_clear_confirm' => 'Yes, Clear All',
        'cart_item_removed' => 'Item removed from cart',

        // Ingredient Pricing
        'cost_per_kg_l' => 'Price per KG / L ($)',
        'cost_per_1kg' => 'Price per 1 KG ($)',
        'cost_per_1l' => 'Price per 1 Liter ($)',
        'cost_per_1pc' => 'Price per 1 Piece ($)',
        'cost_per_base_unit' => 'Cost per Base Unit ($)',

        // Ingredient Categories
        'cat_liquids' => 'Liquids',
        'cat_beans' => 'Beans',
        'cat_packaging' => 'Cups & Packaging',
        'cat_general' => 'General Supplies',

        // Packaging Set Cost
        'packaging_set_cost' => 'Packaging Cost per Set',
        'packaging_modal_title' => 'Packaging Cost per Set Calculator',
        'packaging_modal_sub' => 'Calculate & manage total packaging cost per cup (Cups, Lids, Straws, Sleeves, etc.)',
        'packaging_item_name' => 'Packaging Material',
        'packaging_cost_unit' => 'Cost per Piece ($)',
        'packaging_qty_per_set' => 'Qty / Cup',
        'packaging_subtotal' => 'Subtotal',
        'packaging_total_per_cup' => 'Total Packaging Cost per 1 Cup',
        'packaging_100_cups' => 'Cost for 100 Cups',
        'packaging_add_item_btn' => 'Add Component',
        'packaging_save_btn' => 'Save Packaging Set Cost',
        'packaging_saved_success' => 'Packaging set cost saved successfully!',

        // Ingredient History
        'ingredient_history_title' => 'Deduction & Usage History',
        'ingredient_history_sub' => 'View all sales deductions, orders, and recipes using this ingredient.',
        'btn_history' => 'Deduction History',
        'current_stock_label' => 'Current Stock',
        'total_deducted_sales' => 'Total Sales Deducted',
        'total_orders_used' => 'Total Orders Used',
        'filter_all_logs' => 'All Movements',
        'log_sale_deduct' => 'Sales Deduct',
        'log_restock' => 'Restock',
        'stock_flow' => 'Stock Flow',
        'no_history_logs' => 'No deduction history logged for this ingredient yet.',
    ],

    'km' => [
        // Brand & Theme
        'brand_name' => "Bird's Nest",
        'dark_mode' => 'ងងឹត',
        'light_mode' => 'ភ្លឺ',
        'clock_in' => 'ចូលធ្វើការ',
        'clock_out' => 'ចេញធ្វើការ',
        'logout' => 'ចាកចេញ',
        'good_morning' => 'អរុណសួស្តី',
        'good_afternoon' => 'ទិវាសួស្តី',
        'good_evening' => 'សាយ័ណ្ហសួស្តី',
        'english' => 'English',
        'khmer' => 'Khmer (ខ្មែរ)',
        'language' => 'ភាសា',

        // Navigation
        'nav_dashboard' => 'ផ្ទាំងបញ្ជា',
        'nav_take_order' => 'បង្កើតការកុម្ម៉ង់',
        'nav_orders' => 'បញ្ជីការកុម្ម៉ង់',
        'nav_products' => 'ទំនិញ',
        'nav_categories' => 'ប្រភេទទំនិញ',
        'nav_stock' => 'ស្តុក & សន្និធិ',
        'nav_stock_drinks' => 'ស្តុកភេសជ្ជៈ',
        'nav_raw_ingredients' => 'គ្រឿងផ្សំ',
        'nav_ingredients' => 'គ្រឿងផ្សំ',
        'nav_report' => 'របាយការណ៍',
        'nav_employees' => 'បុគ្គលិក',
        'nav_users' => 'អ្នកប្រើប្រាស់',
        'nav_manage_roles' => 'គ្រប់គ្រងតួនាទី',
        'nav_user_management' => 'គ្រប់គ្រងអ្នកប្រើប្រាស់',
        'nav_settings' => 'ការកំណត់',
        'nav_my_profile' => 'គណនីរបស់ខ្ញុំ',
        'nav_stock_count' => 'រាប់ស្តុក',
        'nav_suppliers' => 'អ្នកផ្គត់ផ្គង់',
        'nav_purchase_orders' => 'បញ្ជាទិញស្តុក',
        'nav_recipes' => 'រូបមន្ត & គ្រឿងផ្សំ',
        'no_recipe' => 'គ្មានរូបមន្ត',
        'nav_loyalty' => 'កម្មវិធីរង្វាន់',
        'nav_announcements' => 'ការប្រកាស',
        'nav_barista_display' => 'ស្ថានីយ៍បារីស្តា',
        'nav_customer_display' => 'អេក្រង់អតិថិជន',

        // Report Submenu
        'nav_reports' => 'របាយការណ៍',
        'nav_daily_report' => 'សេចក្តីសង្ខេបប្រចាំថ្ងៃ',
        'nav_sales_report' => 'ការវិភាគ & នាំចេញ',
        'nav_shift_report' => 'ពិនិត្យវេនធ្វើការ',
        'nav_report_sale' => 'របាយការណ៍លក់',
        'nav_report_product' => 'របាយការណ៍ទំនិញ',
        'nav_inventory_report' => 'របាយការណ៍គ្រឿងផ្សំ',
        'nav_employee_report' => 'របាយការណ៍អ្នកប្រើប្រាស់',

        // Sections
        'sec_orders' => 'ការកុម្ម៉ង់',
        'sec_operations' => 'ប្រតិបត្តិការ',
        'sec_inventory' => 'ស្តុក',
        'sec_procurement' => 'ការទិញស្តុក',
        'sec_reconciliation' => 'ការផ្ទៀងផ្ទាត់សាច់ប្រាក់',
        'sec_loyalty' => 'រង្វាន់អតិថិជន',
        'sec_analytics' => 'ការវិភាគ',
        'sec_staff' => 'បុគ្គលិក',
        'sec_admin' => 'អ្នកគ្រប់គ្រង',
        'sec_account' => 'គណនី',

        // KPIs
        'revenue_today' => 'ចំណូលថ្ងៃនេះ',
        'profit_today' => 'ចំណេញថ្ងៃនេះ',
        'orders_today' => 'ការកុម្ម៉ង់ថ្ងៃនេះ',
        'items_sold' => 'ចំនួនលក់បាន',
        'vs_yesterday' => 'ធៀបនឹងម្សិលមិញ',
        'no_data_yesterday' => 'គ្មានទិន្នន័យម្សិលមិញ',
        'no_sales_today' => 'មិនទាន់មានការលក់ថ្ងៃនេះ',
        'margin' => 'រឹមចំណេញ',
        'completed' => 'បានបញ្ចប់',
        'from_completed_orders' => 'ពីការកុម្ម៉ង់បានបញ្ចប់',
        'view_report' => 'មើលរបាយការណ៍',
        'view_breakdown' => 'មើលការវិភាគ',
        'view_orders' => 'មើលការកុម្ម៉ង់',
        'view_items' => 'មើលមុខទំនិញ',

        // Dashboard Charts
        'profit_loss' => 'ចំណេញ & ខាត',
        'net_profit_today' => 'ប្រាក់ចំណេញសុទ្ធថ្ងៃនេះ',
        'revenue_income' => 'ចំណូលសរុប',
        'cogs_ingredient_cost' => 'ថ្លៃដើមគ្រឿងផ្សំ',
        'margin_rate' => 'អត្រារឹមចំណេញ',
        'gross_margin' => 'ចំណេញដុល',
        'category_sales' => 'ការលក់តាមប្រភេទ',
        'hourly_orders' => 'ការកុម្ម៉ង់តាមម៉ោង',
        'sales_trend' => 'និន្នាការនៃការលក់',
        'today' => 'ថ្ងៃនេះ',
        'last_7_days' => '៧ ថ្ងៃចុងក្រោយ',
        'distribution' => 'ការបែងចែក',
        'orders' => 'ការកុម្ម៉ង់',
        'profit' => 'ចំណេញ',
        'revenue' => 'ចំណូល',

        // POS / Menu
        'search_products' => 'ស្វែងរកភេសជ្ជៈ...',
        'all_categories' => 'គ្រប់ប្រភេទទាំងអស់',
        'top_sellers' => 'មុខទំនិញលក់ដាច់បំផុត',
        'seller_num_1' => 'លក់ដាច់លេខ១',
        'top_pick' => 'ជម្រើសល្អបំផុត',
        'best_seller' => 'លក់ដាច់បំផុត',
        'cart' => 'កន្ត្រកទំនិញ',
        'cart_empty' => 'កន្ត្រកទំនិញទទេ',
        'tap_drink_to_add' => 'ភេសជ្ជៈដែលអ្នកបានជ្រើសរើសនឹងបង្ហាញទីនេះ',
        'subtotal' => 'សរុបដើម',
        'tax' => 'ពន្ធ',
        'total' => 'សរុបចុងក្រោយ',
        'order_type' => 'ប្រភេទការកុម្ម៉ង់',
        'place_order' => 'បញ្ជូនការកុម្ម៉ង់',
        'confirm_order' => 'បញ្ជាក់ការកុម្ម៉ង់',
        'add_to_order' => 'បន្ថែមទៅការកុម្ម៉ង់ #',
        'add_to_cart' => 'បន្ថែមទៅកន្ត្រក',
        'checkout' => 'ទូទាត់ប្រាក់',
        'clear_cart' => 'សម្អាតកន្ត្រក',
        'customer_name' => 'ឈ្មោះអតិថិជន',
        'dine_in' => 'ញ៉ាំនៅហាង',
        'takeaway' => 'ខ្ចប់ទៅផ្ទះ',
        'payment_method' => 'វិធីសាស្ត្រទូទាត់',
        'cash' => 'សាច់ប្រាក់',
        'bakong_khqr' => 'បាគង',
        'pay_later' => 'ជំពាក់ប្រាក់',

        // Customization Modal
        'sweetness' => 'កម្រិតជាតិផ្អែម',
        'ice' => 'កម្រិតទឹកកក',
        'no_ice' => 'គ្មានទឹកកក',
        'less_ice' => 'ទឹកកកតិច',
        'normal_ice' => 'ទឹកកកធម្មតា',
        'more_ice' => 'ទឹកកកច្រើន',

        // Orders Board / View Orders
        'all_orders' => 'ការកុម្ម៉ង់ទាំងអស់',
        'show_all_orders' => 'បង្ហាញការកុម្ម៉ង់ទាំងអស់',
        'new_order' => 'ការកុម្ម៉ង់ថ្មី',
        'in_prep_queue' => 'នៅក្នុងជួររៀបចំ',
        'making' => 'កំពុងធ្វើ',
        'being_prepared' => 'កំពុងត្រូវបានរៀបចំ',
        'complete_order' => 'ការកុម្ម៉ង់បានបញ្ចប់',
        'finished_today' => 'បានបញ្ចប់ថ្ងៃនេះ',
        'overdue_order' => 'ការកុម្ម៉ង់ហួសពេល',
        'over_10_mins' => 'លើសពី ១០ នាទីក្នុងជួរ',
        'total_price' => 'តម្លៃសរុប',
        'total_sales_today' => 'ការលក់សរុបថ្ងៃនេះ',
        'search_orders_ph' => 'ស្វែងរកតាមឈ្មោះអតិថិជន លេខកុម្ម៉ង់ ឬស្ថានភាព...',
        'clear' => 'សម្អាត',
        'col_no' => 'លេខរៀង',
        'col_item' => 'មុខទំនិញ',
        'col_total_price' => 'តម្លៃសរុប',
        'col_time' => 'កាលបរិច្ឆេទ & ម៉ោង',
        'col_status' => 'ស្ថានភាព',
        'col_place_by' => 'បង្កើតដោយ',
        'col_action' => 'សកម្មភាព',
        'view_detail' => 'មើលលម្អិត',
        'reprint' => 'បោះពុម្ពឡើងវិញ',
        'range_all' => 'ទាំងអស់',
        'range_today' => 'ថ្ងៃនេះ',
        'range_this_week' => 'សប្តាហ៍នេះ',
        'range_this_month' => 'ខែនេះ',
        'range_this_year' => 'ឆ្នាំនេះ',
        'item_single' => 'មុខទំនិញ',
        'item_plural' => 'មុខទំនិញ',
        'no_orders_found' => 'រកមិនឃើញការកុម្ម៉ង់ទេ',
        'try_changing_search' => 'សាកល្បងផ្លាស់ប្តូរពាក្យស្វែងរក ឬកាតចម្រោះខាងលើ។',

        // Orders List Statuses
        'order_id' => 'លេខកុម្ម៉ង់ #',
        'customer' => 'អតិថិជន',
        'date_time' => 'កាលបរិច្ឆេទ & ម៉ោង',
        'status' => 'ស្ថានភាព',
        'actions' => 'សកម្មភាព',
        'status_paid' => 'បានទូទាត់',
        'status_pending' => 'រង់ចាំ',
        'status_preparing' => 'កំពុងរៀបចំ',
        'status_completed' => 'បានបញ្ចប់',
        'status_cancelled' => 'បានបោះបង់',
        'status_refunded' => 'បានសងប្រាក់វិញ',

        // Products & Categories
        'manage_categories' => 'គ្រប់គ្រងប្រភេទទំនិញ',
        'catalog' => 'កាតាឡុក',
        'active' => 'សកម្ម',
        'inactive' => 'អសកម្ម',
        'visible_on_menu' => 'បង្ហាញក្នុងម៉ឺនុយ',
        'hidden_from_menu' => 'លាក់ពីម៉ឺនុយ',
        'offers' => 'ជម្រើសបន្ថែម',
        'sweet' => 'ផ្អែម',
        'milk' => 'ទឹកដោះគោ',
        'add_ons' => 'បន្ថែម',
        'on' => 'បើក',
        'off' => 'បិទ',
        'add_product' => 'បន្ថែមទំនិញ',
        'edit_product' => 'កែប្រែទំនិញ',
        'product_name' => 'ឈ្មោះទំនិញ',
        'category' => 'ប្រភេទ',
        'price' => 'តម្លៃ',
        'cost' => 'ថ្លៃដើម',
        'image' => 'រូបភាព',
        'in_stock' => 'មានក្នុងស្តុក',
        'out_of_stock' => 'អស់ពីស្តុក',
        'add_category' => 'បន្ថែមប្រភេទ',
        'category_name' => 'ឈ្មោះប្រភេទ',
        'top_category' => 'ប្រភេទលក់ល្អដាច់គេ',
        'products_on_menu' => 'ទំនិញក្នុងម៉ឺនុយ',
        'off_menu' => 'អសកម្មក្នុងម៉ឺនុយ',
        'search_products_ph' => 'ស្វែងរកទំនិញ... (ចុច /)',

        // Ingredients & Inventory
        'btn_history' => 'ប្រវត្តិ',
        'btn_export_pdf' => 'នាំចេញ PDF',
        'add_ingredient' => 'បន្ថែមគ្រឿងផ្សំ',
        'ingredient_name' => 'ឈ្មោះគ្រឿងផ្សំ',
        'stock_level' => 'កម្រិតស្តុក',
        'unit' => 'ខ្នាត',
        'min_stock' => 'កម្រិតស្តុកអប្បបរមា',
        'low_stock' => 'ស្តុកតិច',
        'available' => 'អាចប្រើបាន',
        'below_minimum' => 'ទាបជាងអប្បបរមា',
        'needs_restock' => 'ត្រូវការបំពេញបន្ថែម',
        'stock_value' => 'តម្លៃស្តុកសរុប',
        'total_investment' => 'ការវិនិយោគសរុប',
        'search_ingredients_ph' => 'ស្វែងរកគ្រឿងផ្សំ... (ចុច /)',
        'cost_per_unit' => 'តម្លៃដើមក្នុងមួយខ្នាត',

        // Employees & Users & Roles
        'total_staff' => 'បុគ្គលិកសរុប',
        'employees_on_record' => 'បុគ្គលិកដែលមានក្នុងបញ្ជី',
        'orders_this_month' => 'ការកុម្ម៉ង់ខែនេះ',
        'all_time' => 'សរុបទាំងអស់',
        'top_this_month' => 'បុគ្គលិកឆ្នើមខែនេះ',
        'no_data_yet' => 'មិនទាន់មានទិន្នន័យ',
        'revenue_served' => 'ចំណូលដែលបានបម្រើ',
        'all_time_all_staff' => 'សរុបទាំងអស់គ្រប់បុគ្គលិក',
        'all_time_orders' => 'ការកុម្ម៉ង់សរុបទាំងអស់',
        'by_all_staff' => 'ដោយគ្រប់បុគ្គលិក',
        'search_emp_ph' => 'ស្វែងរកតាមឈ្មោះ ឬតួនាទី...',
        'all_roles' => 'គ្រប់តួនាទី',
        'add_new_employee' => 'បន្ថែមបុគ្គលិកថ្មី',
        'col_staff_id' => 'អត្តលេខបុគ្គលិក',
        'col_name' => 'ឈ្មោះ',
        'col_role' => 'តួនាទី',
        'col_phone' => 'លេខទូរស័ព្ទ',
        'col_shift' => 'វេនធ្វើការ',
        'shift_morning' => 'ពេលព្រឹក',
        'shift_afternoon' => 'ពេលរសៀល',
        'shift_night' => 'ពេលយប់',

        'users_management' => 'គ្រប់គ្រងអ្នកប្រើប្រាស់',
        'users_management_sub' => 'គ្រប់គ្រងអ្នកប្រើប្រាស់ ប្រព័ន្ធ គណនីអ្នកគ្រប់គ្រង និងសិទ្ធិចូលប្រើប្រាស់',
        'search_user_ph' => 'ស្វែងរកអ្នកប្រើប្រាស់...',
        'add_new_user' => 'បន្ថែមអ្នកប្រើប្រាស់ថ្មី',
        'col_user' => 'អ្នកប្រើប្រាស់',
        'col_emp_name' => 'ឈ្មោះបុគ្គលិក',
        'col_password' => 'ពាក្យសម្ងាត់',
        'btn_change' => 'ផ្លាស់ប្តូរ',
        'badge_you' => 'អ្នក',

        'manage_role_permissions' => 'គ្រប់គ្រងសិទ្ធិតួនាទី',
        'admin_only' => 'សម្រាប់តែ Admin',
        'manage_role_sub' => 'គ្រប់គ្រងទំព័រ និងលក្ខណៈពិសេសដែលតួនាទីនីមួយៗអាចប្រើបាន។ Admin រក្សាសិទ្ធិពេញលេញជានិច្ច។',
        'roles' => 'តួនាទី',
        'permissions' => 'សិទ្ធិប្រើប្រាស់',
        'modules' => 'ម៉ូឌុល',
        'user_overrides' => 'សិទ្ធិពិសេសអ្នកប្រើប្រាស់',
        'create_role' => 'បង្កើតតួនាទី',
        'roles_overview' => 'ទិដ្ឋភាពទូទៅនៃតួនាទី',
        'staff' => 'បុគ្គលិក',

        'add_employee' => 'បន្ថែមបុគ្គលិក',
        'add_user' => 'បន្ថែមអ្នកប្រើប្រាស់',
        'full_name' => 'ឈ្មោះពេញ',
        'role' => 'តួនាទី',
        'username' => 'ឈ្មោះគណនី',
        'phone' => 'លេខទូរស័ព្ទ',
        'created_at' => 'កាលបរិច្ឆេទបង្កើត',
        'role_name' => 'ឈ្មោះតួនាទី',

        // Reports
        'daily_sales_report' => 'របាយការណ៍លក់ប្រចាំថ្ងៃ',
        'product_sales_report' => 'របាយការណ៍លក់តាមទំនិញ',
        'inventory_report' => 'របាយការណ៍ស្តុក',
        'shift_report' => 'របាយការណ៍វេនធ្វើការ',
        'date' => 'កាលបរិច្ឆេទ',
        'total_revenue' => 'ចំណូលសរុប',
        'total_profit' => 'ប្រាក់ចំណេញសរុប',

        // Common Buttons & Messages
        'search' => 'ស្វែងរក',
        'save' => 'រក្សាទុក',
        'cancel' => 'បោះបង់',
        'edit' => 'កែប្រែ',
        'delete' => 'លុប',
        'add' => 'បន្ថែម',
        'refresh' => 'ផ្ទុកឡើងវិញ',
        'view_all' => 'មើលទាំងអស់',
        'no_data' => 'គ្មានទិន្នន័យ',

        // Inventory & Direct Drinks Stock
        'direct_drinks_stock' => 'ស្តុកភេសជ្ជៈ',
        'cans_and_bottles' => 'កំប៉ុង & ដប',
        'raw_ingredients_supplies' => 'គ្រឿងផ្សំ & សម្ភារៈ',
        'recipe_bom' => 'រូបមន្តផលិត',
        'audit_and_logs' => 'ប្រវត្តិ & កំណត់ត្រា',
        'add_canned_bottled_drink' => 'បន្ថែមភេសជ្ជៈដប/កំប៉ុង',
        'add_raw_ingredient' => 'បន្ថែមគ្រឿងផ្សំ',
        'add_ingredient' => 'បន្ថែមគ្រឿងផ្សំថ្មី',
        'quick_restock' => 'បញ្ចូលស្តុករហ័ស',
        'log_waste' => 'កត់ត្រាការខូចខាត/កំពប់',
        'kpi_total' => 'សរុប',
        'kpi_in_stock' => 'មានក្នុងស្តុក',
        'kpi_low_stock' => 'ស្តុកជិតអស់',
        'kpi_out_of_stock' => 'អស់ពីស្តុក',
        'kpi_valuation' => 'តម្លៃសរុប',
        'healthy_stock' => 'ស្តុកគ្រប់គ្រាន់',
        'reorder_soon' => 'ត្រូវកុម្ម៉ង់ថែម',
        'depleted_items' => 'ទំនិញអស់ពីស្តុក',
        'direct_drinks' => 'ភេសជ្ជៈផ្ទាល់',
        'raw_materials' => 'វត្ថុធាតុដើម',
        'products_unit' => 'មុខទំនិញ',
        'ingredients_unit' => 'មុខគ្រឿងផ្សំ',
        'search_drinks_ph' => 'ស្វែងរកភេសជ្ជៈតាមឈ្មោះ (ឧ. Sting, Coke, Water)...',
        'search_ingredients_ph' => 'ស្វែងរកគ្រឿងផ្សំតាមឈ្មោះ ប្រភេទ...',
        'all_categories' => 'ប្រភេទទាំងអស់',
        'all_ingredient_categories' => 'ប្រភេទគ្រឿងផ្សំទាំងអស់',
        'sort_name_asc' => 'ឈ្មោះ: A ដល់ Z',
        'sort_name_desc' => 'ឈ្មោះ: Z ដល់ A',
        'sort_qty_asc' => 'ចំនួន: តិចទៅច្រើន',
        'sort_qty_desc' => 'ចំនួន: ច្រើនទៅតិច',
        'sort_val_desc' => 'តម្លៃសរុបខ្ពស់ជាងគេ',
        'sort_newest' => 'បន្ថែមថ្មីៗ',
        'col_drink_product' => 'ឈ្មោះភេសជ្ជៈ',
        'col_ingredient_details' => 'ព័ត៌មានលម្អិតគ្រឿងផ្សំ',
        'col_ingredient' => 'ឈ្មោះគ្រឿងផ្សំ',
        'col_category' => 'ប្រភេទ',
        'col_unit' => 'ខ្នាត',
        'col_conversion_rate' => 'អត្រាបំប្លែង',
        'col_total_qty' => 'ចំនួនសរុប (ខ្នាត)',
        'col_on_hand_qty' => 'ចំនួនមានក្នុងស្តុក',
        'col_qty_on_hand' => 'ចំនួនមានក្នុងស្តុក',
        'col_alert_threshold' => 'កម្រិតប្រកាសអាសន្ន',
        'col_estimated_capacity' => 'សមត្ថភាពប៉ាន់ស្មាន',
        'col_breakdown' => 'ការបែងចែកកញ្ចប់',
        'col_cost_box_unit' => 'ថ្លៃដើម (ក្នុងមួយកេស / រាយ)',
        'col_sell_price_unit' => 'តម្លៃលក់/រាយ',
        'col_sell_price_box' => 'តម្លៃលក់/កេស',
        'col_cost_unit' => 'ថ្លៃដើមក្នុង១ខ្នាត ($)',
        'col_cost_box' => 'ថ្លៃដើមក្នុង១កេស ($)',
        'cost_price_unit' => 'ថ្លៃដើមក្នុង១ខ្នាត ($)',
        'cost_price_box' => 'ថ្លៃដើមក្នុង១កេស ($)',
        'sell_price_unit' => 'តម្លៃលក់ក្នុង១ខ្នាត ($)',
        'sell_price_box' => 'តម្លៃលក់ក្នុង១កេស ($)',
        'single_unit' => 'ខ្នាតរាយ',
        'package_unit' => 'ខ្នាតកញ្ចប់/កេស',
        'units_per_package' => 'ចំនួនក្នុង១កេស/កញ្ចប់',
        'initial_boxes' => 'ចំនួនកេសដំបូង',
        'loose_units' => 'ចំនួនរាយបន្ថែម',
        'alert_threshold' => 'កម្រិតប្រកាសអាសន្ន',
        'col_status' => 'ស្ថានភាព',
        'col_valuation' => 'តម្លៃសរុប',
        'col_actions' => 'សកម្មភាព',
        'cat_dairy' => 'ទឹកដោះគោ & ទឹក',
        'cat_beans' => 'គ្រាប់កាហ្វេ',
        'cat_syrups' => 'ស៊ីរ៉ូ & រសជាតិ',
        'cat_packaging' => 'កែវ & ការវេចខ្ចប់',
        'cat_bakery' => 'នំ & គ្រឿងបន្ថែម',
        'cat_general' => 'សម្ភារៈទូទៅ',
        'status_in_stock' => 'មានក្នុងស្តុក',
        'status_low_stock' => 'ស្តុកជិតអស់',
        'status_out_of_stock' => 'អស់ពីស្តុក',
        'btn_restock' => 'បញ្ចូលស្តុក',
        'btn_edit' => 'កែប្រែ',
        'btn_delete' => 'លុប',
        'btn_close' => 'បិទ',
        'btn_cancel' => 'បោះបង់',
        'btn_confirm_restock' => 'បញ្ជាក់ការបញ្ចូលស្តុក',
        'btn_update_drink' => 'កែប្រែភេសជ្ជៈ',
        'btn_update_ingredient' => 'កែប្រែគ្រឿងផ្សំ',
        'showing_drinks_count' => 'បង្ហាញភេសជ្ជៈផ្ទាល់',
        'showing_ingredients_count' => 'បង្ហាញគ្រឿងផ្សំ',
        'quantity_added' => 'ចំនួនបន្ថែម',
        'quantity_wasted' => 'ចំនួនខូចខាត/កំពប់',
        'notes' => 'កំណត់សម្គាល់',
        'date' => 'កាលបរិច្ឆេទ',
        'loose' => 'រាយ',
        'full' => 'ពេញ',
        'box' => 'កេស',
        'boxes' => 'កេស',
        'can' => 'កំប៉ុង',
        'cans' => 'កំប៉ុង',
        'bottle' => 'ដប',
        'bottles' => 'ដប',
        'audit_ledger_title' => 'ប្រវត្តិ និងកំណត់ត្រាស្តុកភេសជ្ជៈ',
        'audit_ledger_sub' => 'ការបញ្ចូលស្តុកកេស និងប្រវត្តិសកម្មភាពភេសជ្ជៈថ្មីៗ។',
        'recent_restocks' => 'ការបញ្ចូលស្តុកថ្មីៗ',
        'recent_deductions' => 'ប្រវត្តិដកស្តុកចេញ / លក់ចេញ',
        'recent_waste' => 'ការខូចខាត/បែកបាក់ថ្មីៗ',
        'tab_restocks' => 'ប្រវត្តិបញ្ចូលស្តុក',
        'tab_deduct' => 'ប្រវត្តិដកស្តុក',
        'tab_waste' => 'ប្រវត្តិខូចខាត',
        'recent_restocks' => 'ការបញ្ចូលស្តុកថ្មីៗ',
        'recent_deductions' => 'ការដកស្តុកចេញថ្មីៗ',
        'boxes_added' => 'កេសបន្ថែម',
        'loose_added' => 'រាយបន្ថែម',
        'total_units_added' => 'សរុបរាយ',
        'boxes_deducted' => 'កេសដក',
        'loose_deducted' => 'រាយដក',
        'total_deducted' => 'សរុបដក',
        'units_added' => 'ខ្នាតបន្ថែម',
        'supplier_notes' => 'អ្នកផ្គត់ផ្គង់ / កំណត់សម្គាល់',
        'order_notes' => 'វិក្កយបត្រ / កំណត់សម្គាល់',
        'staff_member' => 'បុគ្គលិក',
        'no_restocks_yet' => 'មិនទាន់មានកំណត់ត្រាបញ្ចូលស្តុកនៅឡើយទេ។',
        'no_deduct_yet' => 'មិនទាន់មានកំណត់ត្រាដកស្តុកនៅឡើយទេ។',
        'no_waste_yet' => 'មិនទាន់មានកំណត់ត្រាខូចខាតនៅឡើយទេ។',
        'filter_date_time' => 'ច្រោះតាមកាលបរិច្ឆេទ & ពេលវេលា',
        'filter_all' => 'ទាំងអស់',
        'filter_today' => 'ថ្ងៃនេះ',
        'filter_yesterday' => 'ម្សិលមិញ',
        'filter_this_week' => 'សប្តាហ៍នេះ',
        'filter_this_month' => 'ខែនេះ',
        'from_date' => 'ចាប់ពីថ្ងៃ',
        'to_date' => 'ដល់ថ្ងៃ',
        'search_drink_order' => 'ស្វែងរកភេសជ្ជៈ, លេខ Order, បុគ្គលិក...',
        'clear_filter' => 'សម្អាត',
        'no_match_filter' => 'មិនមានទិន្នន័យត្រូវនឹងការច្រោះកាលបរិច្ឆេទនេះទេ។',

        // Cash Settlement Modal
        'cpm_modal_title' => 'ការទូទាត់ប្រាក់ (គិតលុយ)',
        'cpm_modal_subtitle' => 'ទទួលប្រាក់ពីអតិថិជន & គណនាប្រាក់អាប់',
        'cpm_summary_title' => 'សង្ខេបការបញ្ជាទិញ',
        'cpm_col_items' => 'មុខទំនិញ',
        'cpm_col_price' => 'តម្លៃ',
        'cpm_col_qty' => 'ចំនួន',
        'cpm_col_total' => 'សរុប',
        'cpm_subtotal' => 'ប្រាក់សរុបដើម',
        'cpm_discount' => 'បញ្ចុះតម្លៃ',
        'cpm_tax' => 'ពន្ធ',
        'cpm_total_due' => 'ប្រាក់ត្រូវទូទាត់សរុប',
        'cpm_payment_details' => 'ព័ត៌មានការទូទាត់',
        'cpm_amount_received' => 'ប្រាក់ទទួលបាន',
        'cpm_quick_cash' => 'គិតរហ័ស',
        'cpm_exact' => 'លុយគត់',
        'cpm_payment_method' => 'វិធីសាស្ត្រទូទាត់',
        'cpm_method_cash' => 'សាច់ប្រាក់ (Cash)',
        'cpm_method_bakong' => 'បាញ់ QR (Bakong KHQR)',
        'cpm_keypad' => 'ក្ដារចុចលេខ',
        'cpm_change_calc' => 'គណនាប្រាក់អាប់',
        'cpm_return_method' => 'ទម្រង់អាប់',
        'cpm_return_change_in' => 'អាប់ជាប្រាក់',
        'cpm_mode_mixed' => 'ដុល្លារ + រៀល',
        'cpm_mode_usd' => 'ដុល្លារ',
        'cpm_mode_khr' => 'រៀល (KHR)',
        'cpm_change_to_return' => 'ប្រាក់ត្រូវអាប់',
        'cpm_cancel' => 'បោះបង់',
        'cpm_apply_payment' => 'ទូទាត់ & បោះពុម្ពវិក្កយបត្រ',
        'cpm_apply_bakong' => 'ទូទាត់ & បង្ហាញ QR',
        'cpm_cancel_order' => 'បោះបង់ការកុម្ម៉ង់',
        'cpm_confirm_received' => 'បញ្ជាក់ថាបានទទួលប្រាក់',
        'cpm_payment_received' => 'បានទទួលការទូទាត់!',
        'cpm_order_settled_bakong' => 'ការកុម្ម៉ង់ត្រូវបានទូទាត់តាម បាគង KHQR រួចរាល់។',
        'cpm_auto_completing' => 'បញ្ចប់ដោយស្វ័យប្រវត្តិក្នុងរយៈពេល',
        'cpm_waiting_bakong' => 'កំពុងរង់ចាំការទូទាត់ពីបាគង...',
        'cpm_khqr_scan_pay' => 'ស្កេនទូទាត់តាម KHQR',
        'cpm_under_10_riel' => 'ក្រោម 10$: អាប់ជាប្រាក់រៀលសុទ្ធ',
        'cpm_exact_amount' => 'លុយគ្រប់',
        'cpm_need_more' => 'ខ្វះ',
        'cpm_bakong_no_change_label' => 'ទូទាត់ KHQR',
        'cpm_exact_no_change' => 'ទូទាត់គ្រប់ចំនួន • មិនបាច់អាប់ប្រាក់ទេ',
        'cpm_digital_payment_title' => 'ការទូទាត់ឌីជីថល (មិនបាច់អាប់ប្រាក់ទេ)',
        'cpm_exact_khqr_total' => 'ទឹកប្រាក់ទូទាត់ជាក់ស្តែង',

        // Cart Item Removal Alert
        'cart_remove_item_title' => 'លុបទំនិញពីកន្ត្រក?',
        'cart_remove_item_msg' => 'តើអ្នកពិតជាចង់លុប «:item» ចេញពីកន្ត្រកមែនទេ?',
        'cart_remove_item_confirm' => 'យល់ព្រមលុប',
        'cart_clear_title' => 'សម្អាតកន្ត្រកទាំងមូល?',
        'cart_clear_msg' => 'តើអ្នកពិតជាចង់លុបទំនិញទាំងអស់ចេញពីកន្ត្រកមែនទេ?',
        'cart_clear_confirm' => 'យល់ព្រមសម្អាត',
        'cart_item_removed' => 'បានលុបទំនិញចេញពីកន្ត្រក',

        // Ingredient Pricing
        'cost_per_kg_l' => 'ថ្លៃដើមក្នុង 1 KG ឬ 1 L ($)',
        'cost_per_1kg' => 'ថ្លៃដើមក្នុង 1 KG ($)',
        'cost_per_1l' => 'ថ្លៃដើមក្នុង 1 Liter ($)',
        'cost_per_1pc' => 'ថ្លៃដើមក្នុង 1 ឯកតា ($)',
        'cost_per_base_unit' => 'ថ្លៃដើមក្នុងមួយខ្នាតគោល ($)',

        // Ingredient Categories
        'cat_liquids' => 'ទឹក',
        'cat_beans' => 'គ្រាប់',
        'cat_packaging' => 'កែវ & ការវេចខ្ចប់',
        'cat_general' => 'សម្ភារទូទៅ',

        // Packaging Set Cost
        'packaging_set_cost' => 'ថ្លៃដើមវេចខ្ចប់សរុប (Cost per Set)',
        'packaging_modal_title' => 'ថ្លៃដើមវេចខ្ចប់សរុបក្នុង 1 ឈុត (Packaging Cost per Set)',
        'packaging_modal_sub' => 'គណនា និងកំណត់ថ្លៃដើមសម្ភារវេចខ្ចប់សរុបក្នុង 1 កែវ (កែវ គម្រប បំពង់បឺត ថង់ ស្រោមដៃកែវ...)',
        'packaging_item_name' => 'ឈ្មោះសម្ភារវេចខ្ចប់',
        'packaging_cost_unit' => 'តម្លៃក្នុង 1 ឯកតា ($)',
        'packaging_qty_per_set' => 'ចំនួនប្រើក្នុង 1 កែវ',
        'packaging_subtotal' => 'សរុប',
        'packaging_total_per_cup' => 'ថ្លៃដើមវេចខ្ចប់សរុបក្នុង 1 កែវ',
        'packaging_100_cups' => 'ថ្លៃដើមក្នុង 100 កែវ',
        'packaging_1000_cups' => 'ថ្លៃដើមក្នុង 1,000 កែវ',
        'packaging_add_item_btn' => 'បន្ថែមសម្ភារវេចខ្ចប់',
        'packaging_save_btn' => 'រក្សាទុកថ្លៃដើមវេចខ្ចប់',
        'packaging_saved_success' => 'បានរក្សាទុកថ្លៃដើមវេចខ្ចប់សរុបដោយជោគជ័យ!',

        // Ingredient History
        'ingredient_history_title' => 'ប្រវត្តិប្រើប្រាស់ & កាត់ស្តុក',
        'ingredient_history_sub' => 'ពិនិត្យមើលរាល់ការកាត់ស្តុកតាម Order នីមួយៗ និងមុខភេសជ្ជៈដែលបានប្រើប្រាស់',
        'btn_history' => 'ប្រវត្តិប្រើប្រាស់ & កាត់ស្តុក',
        'current_stock_label' => 'ស្តុកបច្ចុប្បន្ន',
        'total_deducted_sales' => 'កាត់តាមការលក់សរុប',
        'total_orders_used' => 'ចំនួន Order ប្រើប្រាស់',
        'filter_all_logs' => 'ទាំងអស់',
        'log_sale_deduct' => 'កាត់តាមការលក់',
        'log_restock' => 'ថែមស្តុក',
        'stock_flow' => 'ស្តុកដើម → ស្តុកនៅសល់',
        'no_history_logs' => 'មិនទាន់មានប្រវត្តិកាត់ស្តុកសម្រាប់គ្រឿងផ្សំនេះនៅឡើយទេ',
    ]
];

/**
 * Get translated string for current language.
 * Falls back to English string, or key if missing.
 */
if (!function_exists('__')) {
    function __(string $key, string $fallback = ''): string {
        global $_translations, $_current_lang;
        if (isset($_translations[$_current_lang][$key])) {
            return $_translations[$_current_lang][$key];
        }
        if (isset($_translations['en'][$key])) {
            return $_translations['en'][$key];
        }
        return $fallback !== '' ? $fallback : $key;
    }
}

/**
 * Return current active language code ('en' or 'km')
 */
if (!function_exists('current_lang')) {
    function current_lang(): string {
        global $_current_lang;
        return $_current_lang ?? 'en';
    }
}
?>
