<?php
// Multi-language translation helper for Bird's Nest Coffee Application
if (session_status() === PHP_SESSION_NONE) {
    session_start();
}

// Detect language setting (Session -> Cookie -> Default 'en')
if (!isset($_SESSION['lang'])) {
    $_SESSION['lang'] = $_COOKIE['lang'] ?? 'en';
}

$_current_lang = in_array($_SESSION['lang'], ['en', 'km'], true) ? $_SESSION['lang'] : 'en';

$_translations = [
    'en' => [
        // Brand & Theme
        'brand_name' => "Bird's Nest",
        'dark_mode' => 'Dark',
        'light_mode' => 'Light',
        'clock_in' => 'Clock In',
        'clock_out' => 'Clock Out',
        'logout' => 'Logout',
        'good_morning' => 'Good morning',
        'good_afternoon' => 'Good afternoon',
        'good_evening' => 'Good evening',
        'english' => 'English',
        'khmer' => 'Khmer (ខ្មែរ)',
        'language' => 'Language',

        // Navigation
        'nav_dashboard' => 'Dashboard',
        'nav_take_order' => 'Take Order',
        'nav_orders' => 'Orders',
        'nav_products' => 'Products',
        'nav_categories' => 'Categories',
        'nav_ingredients' => 'Ingredients',
        'nav_report' => 'Report',
        'nav_employees' => 'Employees',
        'nav_users' => 'Users',
        'nav_manage_roles' => 'Manage Roles',
        'nav_settings' => 'Settings',
        'nav_my_profile' => 'My Profile',
        'nav_stock_count' => 'Stock Count',
        'nav_suppliers' => 'Suppliers',
        'nav_purchase_orders' => 'Purchase Orders',
        'nav_recipes' => 'Recipes',
        'nav_loyalty' => 'Loyalty Rewards',
        'nav_announcements' => 'Announcements',
        'nav_barista_display' => 'Barista Station',
        'nav_customer_display' => 'Customer Display',

        // Report Submenu
        'nav_report_sale' => 'Report Sale',
        'nav_report_product' => 'Report Product',
        'nav_inventory_report' => 'Inventory',
        'nav_employee_report' => 'Employee',

        // Sections
        'sec_orders' => 'Orders',
        'sec_operations' => 'Operations',
        'sec_inventory' => 'Inventory',
        'sec_procurement' => 'Procurement',
        'sec_reconciliation' => 'Reconciliation',
        'sec_loyalty' => 'Loyalty',
        'sec_analytics' => 'Analytics',
        'sec_staff' => 'Staff',
        'sec_admin' => 'Admin',
        'sec_account' => 'Account',

        // KPIs
        'revenue_today' => 'Revenue Today',
        'profit_today' => 'Profit Today',
        'orders_today' => 'Orders Today',
        'items_sold' => 'Items Sold',
        'vs_yesterday' => 'vs yesterday',
        'no_data_yesterday' => 'No data yesterday',
        'no_sales_today' => 'No sales yet today',
        'margin' => 'margin',
        'completed' => 'completed',
        'from_completed_orders' => 'from completed orders',
        'view_report' => 'View report',
        'view_breakdown' => 'View breakdown',
        'view_orders' => 'View orders',
        'view_items' => 'View items',

        // Dashboard Charts
        'profit_loss' => 'Profit & Loss',
        'net_profit_today' => 'NET PROFIT TODAY',
        'revenue_income' => 'REVENUE / INCOME',
        'cogs_ingredient_cost' => 'COGS / INGREDIENT COST',
        'margin_rate' => 'Margin Rate',
        'gross_margin' => 'Gross Profit',
        'category_sales' => 'Category Sales',
        'hourly_orders' => 'Hourly Orders',
        'sales_trend' => 'Sales Trend',
        'today' => 'Today',
        'last_7_days' => 'Last 7 Days',
        'distribution' => 'Distribution',
        'orders' => 'Orders',
        'profit' => 'Profit',
        'revenue' => 'Revenue',

        // POS / Menu
        'search_products' => 'Search drinks...',
        'all_categories' => 'All Categories',
        'top_sellers' => 'Top Sellers',
        'seller_num_1' => '#1 Seller',
        'top_pick' => 'Top Pick',
        'best_seller' => 'Best Seller',
        'cart' => 'Cart',
        'cart_empty' => 'Cart is empty',
        'tap_drink_to_add' => 'Tap a drink to add it',
        'subtotal' => 'Subtotal',
        'tax' => 'Tax',
        'total' => 'Total',
        'order_type' => 'Order Type',
        'place_order' => 'Place Order',
        'confirm_order' => 'Confirm Order',
        'add_to_order' => 'Add to Order #',
        'add_to_cart' => 'Add to Cart',
        'checkout' => 'Checkout',
        'clear_cart' => 'Clear Cart',
        'customer_name' => 'Customer Name',
        'dine_in' => 'Drink In',
        'takeaway' => 'Drink Out',
        'payment_method' => 'Payment Method',
        'cash' => 'Cash',
        'bakong_khqr' => 'Bakong',
        'pay_later' => 'Pay Later',

        // Customization Modal
        'sweetness' => 'Sugar',
        'ice' => 'Ice',
        'no_ice' => 'No Ice',
        'less_ice' => 'Less Ice',
        'normal_ice' => 'Normal Ice',
        'more_ice' => 'More Ice',

        // Orders Board / View Orders
        'all_orders' => 'All Order',
        'show_all_orders' => 'Show all orders',
        'new_order' => 'New Order',
        'in_prep_queue' => 'In preparation queue',
        'making' => 'Making',
        'being_prepared' => 'Being prepared',
        'complete_order' => 'Complete Order',
        'finished_today' => 'Finished today',
        'overdue_order' => 'Overdue Order',
        'over_10_mins' => 'Over 10 mins in queue',
        'total_price' => 'Total Price',
        'total_sales_today' => 'Total sales today',
        'search_orders_ph' => 'Search by customer name, order #, or status...',
        'clear' => 'Clear',
        'col_no' => 'No.',
        'col_item' => 'ITEM',
        'col_total_price' => 'Total Price',
        'col_time' => 'DATE & TIME',
        'col_status' => 'Status',
        'col_place_by' => 'Place By',
        'col_action' => 'Action',
        'view_detail' => 'View Detail',
        'reprint' => 'Reprint',
        'range_all' => 'All Time',
        'range_today' => 'Today',
        'range_this_week' => 'This Week',
        'range_this_month' => 'This Month',
        'range_this_year' => 'This Year',
        'item_single' => 'item',
        'item_plural' => 'items',
        'no_orders_found' => 'No orders found',
        'try_changing_search' => 'Try changing search query or header filter card.',

        // Orders List Statuses
        'order_id' => 'Order #',
        'customer' => 'Customer',
        'date_time' => 'Date & Time',
        'status' => 'Status',
        'actions' => 'Actions',
        'status_paid' => 'Paid',
        'status_pending' => 'Pending',
        'status_preparing' => 'Preparing',
        'status_completed' => 'Completed',
        'status_cancelled' => 'Cancelled',
        'status_refunded' => 'Refunded',

        // Products & Categories
        'manage_categories' => 'Manage Categories',
        'catalog' => 'Catalog',
        'active' => 'Active',
        'inactive' => 'Inactive',
        'visible_on_menu' => 'Visible on menu',
        'hidden_from_menu' => 'Hidden from menu',
        'offers' => 'Offers',
        'sweet' => 'Sweet',
        'milk' => 'Milk',
        'add_ons' => 'Add-ons',
        'on' => 'On',
        'off' => 'Off',
        'add_product' => 'Add Product',
        'edit_product' => 'Edit Product',
        'product_name' => 'Product Name',
        'category' => 'Category',
        'price' => 'Price',
        'cost' => 'Cost',
        'image' => 'Image',
        'in_stock' => 'In Stock',
        'out_of_stock' => 'Out of Stock',
        'add_category' => 'Add Category',
        'category_name' => 'Category Name',
        'top_category' => 'Top Category',
        'products_on_menu' => 'products on menu',
        'off_menu' => 'items off menu',
        'search_products_ph' => 'Search products… (Press /)',

        // Ingredients & Inventory
        'btn_history' => 'History',
        'btn_export_pdf' => 'Export PDF',
        'add_ingredient' => 'Add Ingredient',
        'ingredient_name' => 'Ingredient Name',
        'stock_level' => 'Stock Level',
        'unit' => 'Unit',
        'min_stock' => 'Reorder Level',
        'low_stock' => 'Low Stock',
        'available' => 'Available',
        'below_minimum' => 'Below minimum',
        'needs_restock' => 'Needs restock',
        'stock_value' => 'Stock Value',
        'total_investment' => 'Total investment',
        'search_ingredients_ph' => 'Search ingredients… (Press /)',
        'cost_per_unit' => 'Cost Per Unit',

        // Employees & Users & Roles
        'total_staff' => 'Total Staff',
        'employees_on_record' => 'Employees on record',
        'orders_this_month' => 'Orders This Month',
        'all_time' => 'all-time',
        'top_this_month' => 'Top This Month',
        'no_data_yet' => 'No data yet',
        'revenue_served' => 'Revenue Served',
        'all_time_all_staff' => 'All-time, all staff',
        'all_time_orders' => 'All-Time Orders',
        'by_all_staff' => 'By all staff',
        'search_emp_ph' => 'Search by name or job title…',
        'all_roles' => 'All Roles',
        'add_new_employee' => 'Add New Employee',
        'col_staff_id' => 'Staff ID',
        'col_name' => 'Name',
        'col_role' => 'Role',
        'col_phone' => 'Phone',
        'col_shift' => 'Shift',
        'shift_morning' => 'Morning',
        'shift_afternoon' => 'Afternoon',
        'shift_night' => 'Night',

        'users_management' => 'Users Management',
        'users_management_sub' => 'Manage system users, administrator accounts and access privileges',
        'search_user_ph' => 'Search user...',
        'add_new_user' => 'Add New User',
        'col_user' => 'User',
        'col_emp_name' => 'Employee Name',
        'col_password' => 'Password',
        'btn_change' => 'Change',
        'badge_you' => 'You',

        'manage_role_permissions' => 'Manage Role Permissions',
        'admin_only' => 'Admin Only',
        'manage_role_sub' => 'Control which pages and features each role can access. Admin always retains full access.',
        'roles' => 'Roles',
        'permissions' => 'Permissions',
        'modules' => 'Modules',
        'user_overrides' => 'User Overrides',
        'create_role' => 'Create Role',
        'roles_overview' => 'Roles Overview',
        'staff' => 'staff',

        'add_employee' => 'Add Employee',
        'add_user' => 'Add User',
        'full_name' => 'Full Name',
        'role' => 'Role',
        'username' => 'Username',
        'phone' => 'Phone Number',
        'created_at' => 'Created Date',
        'role_name' => 'Role Name',

        // Reports
        'daily_sales_report' => 'Daily Sales Report',
        'product_sales_report' => 'Product Sales Report',
        'inventory_report' => 'Inventory Report',
        'shift_report' => 'Shift Report',
        'date' => 'Date',
        'total_revenue' => 'Total Revenue',
        'total_profit' => 'Total Profit',

        // Common Buttons & Messages
        'search' => 'Search',
        'save' => 'Save',
        'cancel' => 'Cancel',
        'edit' => 'Edit',
        'delete' => 'Delete',
        'add' => 'Add',
        'refresh' => 'Refresh',
        'view_all' => 'View all',
        'no_data' => 'No data available',
    ],

    'km' => [
        // Brand & Theme
        'brand_name' => "Bird's Nest",
        'dark_mode' => 'ងងឹត',
        'light_mode' => 'ភ្លឺ',
        'clock_in' => 'ចូលធ្វើការ',
        'clock_out' => 'ចេញធ្វើការ',
        'logout' => 'ចាកចេញ',
        'good_morning' => 'អរុណសួស្តី',
        'good_afternoon' => 'ទិវាសួស្តី',
        'good_evening' => 'សាយ័ណ្ហសួស្តី',
        'english' => 'English',
        'khmer' => 'Khmer (ខ្មែរ)',
        'language' => 'ភាសា',

        // Navigation
        'nav_dashboard' => 'ផ្ទាំងបញ្ជា',
        'nav_take_order' => 'បង្កើតការកុម្ម៉ង់',
        'nav_orders' => 'បញ្ជីការកុម្ម៉ង់',
        'nav_products' => 'ទំនិញ',
        'nav_categories' => 'ប្រភេទទំនិញ',
        'nav_ingredients' => 'គ្រឿងផ្សំ',
        'nav_report' => 'របាយការណ៍',
        'nav_employees' => 'បុគ្គលិក',
        'nav_users' => 'អ្នកប្រើប្រាស់',
        'nav_manage_roles' => 'គ្រប់គ្រងតួនាទី',
        'nav_settings' => 'ការកំណត់',
        'nav_my_profile' => 'គណនីរបស់ខ្ញុំ',
        'nav_stock_count' => 'រាប់ស្តុក',
        'nav_suppliers' => 'អ្នកផ្គត់ផ្គង់',
        'nav_purchase_orders' => 'បញ្ជាទិញស្តុក',
        'nav_recipes' => 'រូបមន្ត',
        'nav_loyalty' => 'កម្មវិធីរង្វាន់',
        'nav_announcements' => 'ការប្រកាស',
        'nav_barista_display' => 'ស្ថានីយ៍បារីស្តា',
        'nav_customer_display' => 'អេក្រង់អតិថិជន',

        // Report Submenu
        'nav_report_sale' => 'របាយការណ៍លក់',
        'nav_report_product' => 'របាយការណ៍ទំនិញ',
        'nav_inventory_report' => 'របាយការណ៍ស្តុក',
        'nav_employee_report' => 'របាយការណ៍បុគ្គលិក',

        // Sections
        'sec_orders' => 'ការកុម្ម៉ង់',
        'sec_operations' => 'ប្រតិបត្តិការ',
        'sec_inventory' => 'ស្តុក',
        'sec_procurement' => 'ការទិញស្តុក',
        'sec_reconciliation' => 'ការផ្ទៀងផ្ទាត់សាច់ប្រាក់',
        'sec_loyalty' => 'រង្វាន់អតិថិជន',
        'sec_analytics' => 'ការវិភាគ',
        'sec_staff' => 'បុគ្គលិក',
        'sec_admin' => 'អ្នកគ្រប់គ្រង',
        'sec_account' => 'គណនី',

        // KPIs
        'revenue_today' => 'ចំណូលថ្ងៃនេះ',
        'profit_today' => 'ចំណេញថ្ងៃនេះ',
        'orders_today' => 'ការកុម្ម៉ង់ថ្ងៃនេះ',
        'items_sold' => 'ចំនួនលក់បាន',
        'vs_yesterday' => 'ធៀបនឹងម្សិលមិញ',
        'no_data_yesterday' => 'គ្មានទិន្នន័យម្សិលមិញ',
        'no_sales_today' => 'មិនទាន់មានការលក់ថ្ងៃនេះ',
        'margin' => 'រឹមចំណេញ',
        'completed' => 'បានបញ្ចប់',
        'from_completed_orders' => 'ពីការកុម្ម៉ង់បានបញ្ចប់',
        'view_report' => 'មើលរបាយការណ៍',
        'view_breakdown' => 'មើលការវិភាគ',
        'view_orders' => 'មើលការកុម្ម៉ង់',
        'view_items' => 'មើលមុខទំនិញ',

        // Dashboard Charts
        'profit_loss' => 'ចំណេញ & ខាត',
        'net_profit_today' => 'ប្រាក់ចំណេញសុទ្ធថ្ងៃនេះ',
        'revenue_income' => 'ចំណូលសរុប',
        'cogs_ingredient_cost' => 'ថ្លៃដើមគ្រឿងផ្សំ',
        'margin_rate' => 'អត្រារឹមចំណេញ',
        'gross_margin' => 'ចំណេញដុល',
        'category_sales' => 'ការលក់តាមប្រភេទ',
        'hourly_orders' => 'ការកុម្ម៉ង់តាមម៉ោង',
        'sales_trend' => 'និន្នាការនៃការលក់',
        'today' => 'ថ្ងៃនេះ',
        'last_7_days' => '៧ ថ្ងៃចុងក្រោយ',
        'distribution' => 'ការបែងចែក',
        'orders' => 'ការកុម្ម៉ង់',
        'profit' => 'ចំណេញ',
        'revenue' => 'ចំណូល',

        // POS / Menu
        'search_products' => 'ស្វែងរកភេសជ្ជៈ...',
        'all_categories' => 'គ្រប់ប្រភេទទាំងអស់',
        'top_sellers' => 'មុខទំនិញលក់ដាច់បំផុត',
        'seller_num_1' => 'លក់ដាច់លេខ១',
        'top_pick' => 'ជម្រើសល្អបំផុត',
        'best_seller' => 'លក់ដាច់បំផុត',
        'cart' => 'កន្ត្រកទំនិញ',
        'cart_empty' => 'កន្ត្រកទំនិញទទេ',
        'tap_drink_to_add' => 'ភេសជ្ជៈដែលអ្នកបានជ្រើសរើសនឹងបង្ហាញទីនេះ',
        'subtotal' => 'សរុបដើម',
        'tax' => 'ពន្ធ',
        'total' => 'សរុបចុងក្រោយ',
        'order_type' => 'ប្រភេទការកុម្ម៉ង់',
        'place_order' => 'បញ្ជូនការកុម្ម៉ង់',
        'confirm_order' => 'បញ្ជាក់ការកុម្ម៉ង់',
        'add_to_order' => 'បន្ថែមទៅការកុម្ម៉ង់ #',
        'add_to_cart' => 'បន្ថែមទៅកន្ត្រក',
        'checkout' => 'ទូទាត់ប្រាក់',
        'clear_cart' => 'សម្អាតកន្ត្រក',
        'customer_name' => 'ឈ្មោះអតិថិជន',
        'dine_in' => 'ញ៉ាំនៅហាង',
        'takeaway' => 'ខ្ចប់ទៅផ្ទះ',
        'payment_method' => 'វិធីសាស្ត្រទូទាត់',
        'cash' => 'សាច់ប្រាក់',
        'bakong_khqr' => 'បាគង',
        'pay_later' => 'ជំពាក់ប្រាក់',

        // Customization Modal
        'sweetness' => 'កម្រិតជាតិផ្អែម',
        'ice' => 'កម្រិតទឹកកក',
        'no_ice' => 'គ្មានទឹកកក',
        'less_ice' => 'ទឹកកកតិច',
        'normal_ice' => 'ទឹកកកធម្មតា',
        'more_ice' => 'ទឹកកកច្រើន',

        // Orders Board / View Orders
        'all_orders' => 'ការកុម្ម៉ង់ទាំងអស់',
        'show_all_orders' => 'បង្ហាញការកុម្ម៉ង់ទាំងអស់',
        'new_order' => 'ការកុម្ម៉ង់ថ្មី',
        'in_prep_queue' => 'នៅក្នុងជួររៀបចំ',
        'making' => 'កំពុងធ្វើ',
        'being_prepared' => 'កំពុងត្រូវបានរៀបចំ',
        'complete_order' => 'ការកុម្ម៉ង់បានបញ្ចប់',
        'finished_today' => 'បានបញ្ចប់ថ្ងៃនេះ',
        'overdue_order' => 'ការកុម្ម៉ង់ហួសពេល',
        'over_10_mins' => 'លើសពី ១០ នាទីក្នុងជួរ',
        'total_price' => 'តម្លៃសរុប',
        'total_sales_today' => 'ការលក់សរុបថ្ងៃនេះ',
        'search_orders_ph' => 'ស្វែងរកតាមឈ្មោះអតិថិជន លេខកុម្ម៉ង់ ឬស្ថានភាព...',
        'clear' => 'សម្អាត',
        'col_no' => 'លេខរៀង',
        'col_item' => 'មុខទំនិញ',
        'col_total_price' => 'តម្លៃសរុប',
        'col_time' => 'កាលបរិច្ឆេទ & ម៉ោង',
        'col_status' => 'ស្ថានភាព',
        'col_place_by' => 'បង្កើតដោយ',
        'col_action' => 'សកម្មភាព',
        'view_detail' => 'មើលលម្អិត',
        'reprint' => 'បោះពុម្ពឡើងវិញ',
        'range_all' => 'ទាំងអស់',
        'range_today' => 'ថ្ងៃនេះ',
        'range_this_week' => 'សប្តាហ៍នេះ',
        'range_this_month' => 'ខែនេះ',
        'range_this_year' => 'ឆ្នាំនេះ',
        'item_single' => 'មុខទំនិញ',
        'item_plural' => 'មុខទំនិញ',
        'no_orders_found' => 'រកមិនឃើញការកុម្ម៉ង់ទេ',
        'try_changing_search' => 'សាកល្បងផ្លាស់ប្តូរពាក្យស្វែងរក ឬកាតចម្រោះខាងលើ។',

        // Orders List Statuses
        'order_id' => 'លេខកុម្ម៉ង់ #',
        'customer' => 'អតិថិជន',
        'date_time' => 'កាលបរិច្ឆេទ & ម៉ោង',
        'status' => 'ស្ថានភាព',
        'actions' => 'សកម្មភាព',
        'status_paid' => 'បានទូទាត់',
        'status_pending' => 'រង់ចាំ',
        'status_preparing' => 'កំពុងរៀបចំ',
        'status_completed' => 'បានបញ្ចប់',
        'status_cancelled' => 'បានបោះបង់',
        'status_refunded' => 'បានសងប្រាក់វិញ',

        // Products & Categories
        'manage_categories' => 'គ្រប់គ្រងប្រភេទទំនិញ',
        'catalog' => 'កាតាឡុក',
        'active' => 'សកម្ម',
        'inactive' => 'អសកម្ម',
        'visible_on_menu' => 'បង្ហាញក្នុងម៉ឺនុយ',
        'hidden_from_menu' => 'លាក់ពីម៉ឺនុយ',
        'offers' => 'ជម្រើសបន្ថែម',
        'sweet' => 'ផ្អែម',
        'milk' => 'ទឹកដោះគោ',
        'add_ons' => 'បន្ថែម',
        'on' => 'បើក',
        'off' => 'បិទ',
        'add_product' => 'បន្ថែមទំនិញ',
        'edit_product' => 'កែប្រែទំនិញ',
        'product_name' => 'ឈ្មោះទំនិញ',
        'category' => 'ប្រភេទ',
        'price' => 'តម្លៃ',
        'cost' => 'ថ្លៃដើម',
        'image' => 'រូបភាព',
        'in_stock' => 'មានក្នុងស្តុក',
        'out_of_stock' => 'អស់ពីស្តុក',
        'add_category' => 'បន្ថែមប្រភេទ',
        'category_name' => 'ឈ្មោះប្រភេទ',
        'top_category' => 'ប្រភេទលក់ល្អដាច់គេ',
        'products_on_menu' => 'ទំនិញក្នុងម៉ឺនុយ',
        'off_menu' => 'អសកម្មក្នុងម៉ឺនុយ',
        'search_products_ph' => 'ស្វែងរកទំនិញ... (ចុច /)',

        // Ingredients & Inventory
        'btn_history' => 'ប្រវត្តិ',
        'btn_export_pdf' => 'នាំចេញ PDF',
        'add_ingredient' => 'បន្ថែមគ្រឿងផ្សំ',
        'ingredient_name' => 'ឈ្មោះគ្រឿងផ្សំ',
        'stock_level' => 'កម្រិតស្តុក',
        'unit' => 'ខ្នាត',
        'min_stock' => 'កម្រិតស្តុកអប្បបរមា',
        'low_stock' => 'ស្តុកតិច',
        'available' => 'អាចប្រើបាន',
        'below_minimum' => 'ទាបជាងអប្បបរមា',
        'needs_restock' => 'ត្រូវការបំពេញបន្ថែម',
        'stock_value' => 'តម្លៃស្តុកសរុប',
        'total_investment' => 'ការវិនិយោគសរុប',
        'search_ingredients_ph' => 'ស្វែងរកគ្រឿងផ្សំ... (ចុច /)',
        'cost_per_unit' => 'តម្លៃដើមក្នុងមួយខ្នាត',

        // Employees & Users & Roles
        'total_staff' => 'បុគ្គលិកសរុប',
        'employees_on_record' => 'បុគ្គលិកដែលមានក្នុងបញ្ជី',
        'orders_this_month' => 'ការកុម្ម៉ង់ខែនេះ',
        'all_time' => 'សរុបទាំងអស់',
        'top_this_month' => 'បុគ្គលិកឆ្នើមខែនេះ',
        'no_data_yet' => 'មិនទាន់មានទិន្នន័យ',
        'revenue_served' => 'ចំណូលដែលបានបម្រើ',
        'all_time_all_staff' => 'សរុបទាំងអស់គ្រប់បុគ្គលិក',
        'all_time_orders' => 'ការកុម្ម៉ង់សរុបទាំងអស់',
        'by_all_staff' => 'ដោយគ្រប់បុគ្គលិក',
        'search_emp_ph' => 'ស្វែងរកតាមឈ្មោះ ឬតួនាទី...',
        'all_roles' => 'គ្រប់តួនាទី',
        'add_new_employee' => 'បន្ថែមបុគ្គលិកថ្មី',
        'col_staff_id' => 'អត្តលេខបុគ្គលិក',
        'col_name' => 'ឈ្មោះ',
        'col_role' => 'តួនាទី',
        'col_phone' => 'លេខទូរស័ព្ទ',
        'col_shift' => 'វេនធ្វើការ',
        'shift_morning' => 'ពេលព្រឹក',
        'shift_afternoon' => 'ពេលរសៀល',
        'shift_night' => 'ពេលយប់',

        'users_management' => 'គ្រប់គ្រងអ្នកប្រើប្រាស់',
        'users_management_sub' => 'គ្រប់គ្រងអ្នកប្រើប្រាស់ ប្រព័ន្ធ គណនីអ្នកគ្រប់គ្រង និងសិទ្ធិចូលប្រើប្រាស់',
        'search_user_ph' => 'ស្វែងរកអ្នកប្រើប្រាស់...',
        'add_new_user' => 'បន្ថែមអ្នកប្រើប្រាស់ថ្មី',
        'col_user' => 'អ្នកប្រើប្រាស់',
        'col_emp_name' => 'ឈ្មោះបុគ្គលិក',
        'col_password' => 'ពាក្យសម្ងាត់',
        'btn_change' => 'ផ្លាស់ប្តូរ',
        'badge_you' => 'អ្នក',

        'manage_role_permissions' => 'គ្រប់គ្រងសិទ្ធិតួនាទី',
        'admin_only' => 'សម្រាប់តែ Admin',
        'manage_role_sub' => 'គ្រប់គ្រងទំព័រ និងលក្ខណៈពិសេសដែលតួនាទីនីមួយៗអាចប្រើបាន។ Admin រក្សាសិទ្ធិពេញលេញជានិច្ច។',
        'roles' => 'តួនាទី',
        'permissions' => 'សិទ្ធិប្រើប្រាស់',
        'modules' => 'ម៉ូឌុល',
        'user_overrides' => 'សិទ្ធិពិសេសអ្នកប្រើប្រាស់',
        'create_role' => 'បង្កើតតួនាទី',
        'roles_overview' => 'ទិដ្ឋភាពទូទៅនៃតួនាទី',
        'staff' => 'បុគ្គលិក',

        'add_employee' => 'បន្ថែមបុគ្គលិក',
        'add_user' => 'បន្ថែមអ្នកប្រើប្រាស់',
        'full_name' => 'ឈ្មោះពេញ',
        'role' => 'តួនាទី',
        'username' => 'ឈ្មោះគណនី',
        'phone' => 'លេខទូរស័ព្ទ',
        'created_at' => 'កាលបរិច្ឆេទបង្កើត',
        'role_name' => 'ឈ្មោះតួនាទី',

        // Reports
        'daily_sales_report' => 'របាយការណ៍លក់ប្រចាំថ្ងៃ',
        'product_sales_report' => 'របាយការណ៍លក់តាមទំនិញ',
        'inventory_report' => 'របាយការណ៍ស្តុក',
        'shift_report' => 'របាយការណ៍វេនធ្វើការ',
        'date' => 'កាលបរិច្ឆេទ',
        'total_revenue' => 'ចំណូលសរុប',
        'total_profit' => 'ប្រាក់ចំណេញសរុប',

        // Common Buttons & Messages
        'search' => 'ស្វែងរក',
        'save' => 'រក្សាទុក',
        'cancel' => 'បោះបង់',
        'edit' => 'កែប្រែ',
        'delete' => 'លុប',
        'add' => 'បន្ថែម',
        'refresh' => 'ផ្ទុកឡើងវិញ',
        'view_all' => 'មើលទាំងអស់',
        'no_data' => 'គ្មានទិន្នន័យ',
    ]
];

/**
 * Get translated string for current language.
 * Falls back to English string, or key if missing.
 */
if (!function_exists('__')) {
    function __(string $key, string $fallback = ''): string {
        global $_translations, $_current_lang;
        if (isset($_translations[$_current_lang][$key])) {
            return $_translations[$_current_lang][$key];
        }
        if (isset($_translations['en'][$key])) {
            return $_translations['en'][$key];
        }
        return $fallback !== '' ? $fallback : $key;
    }
}

/**
 * Return current active language code ('en' or 'km')
 */
if (!function_exists('current_lang')) {
    function current_lang(): string {
        global $_current_lang;
        return $_current_lang ?? 'en';
    }
}
?>
