<?php
/**
 * Product Sales Report - Print & PDF Export supporting English and Khmer.
 */
require 'auth.php';
require 'config.php';
require_once 'lang.php';
require_once 'dompdf/dompdf/autoload.inc.php';

use Dompdf\Dompdf;
use Dompdf\Options;

if (!can('report')) { header("Location: dashboard.php?denied=1"); exit; }

date_default_timezone_set('Asia/Phnom_Penh');

function he($s) { return htmlspecialchars((string)$s, ENT_QUOTES, 'UTF-8'); }

// ── Language Detection ──
$lang = is_string($_GET['lang'] ?? null) ? trim($_GET['lang']) : current_lang();
$isKm = ($lang === 'km');

$lbl_cafe_title   = 'The Bird Nest Café';
$lbl_report_prod  = $isKm ? 'របាយការណ៍ទំនិញ' : 'Report Product';
$lbl_period       = $isKm ? 'រយៈពេល:' : 'Period:';
$lbl_to           = $isKm ? 'ដល់' : 'to';
$lbl_generated    = $isKm ? 'បង្កើតនៅ:' : 'Generated:';
$lbl_generated_by = $isKm ? 'បង្កើតដោយ:' : 'Generated by:';
$lbl_table_title  = $isKm ? 'តារាងរបាយការណ៍ទំនិញ' : 'PRODUCTS REPORT TABLE';

$lbl_col_no       = $isKm ? 'ល.រ' : 'No';
$lbl_col_pname    = $isKm ? 'ឈ្មោះទំនិញ' : 'Product Name';
$lbl_col_cat      = $isKm ? 'ប្រភេទ' : 'Category';
$lbl_col_qty      = $isKm ? 'ចំនួនលក់' : 'QTY Sold';
$lbl_col_price    = $isKm ? 'តម្លៃ/កែវ' : 'Price/Cup';
$lbl_col_disc     = $isKm ? 'បញ្ចុះតម្លៃ' : 'Disc';
$lbl_col_rev      = $isKm ? 'ចំណូលសរុប' : 'Total Revenue';
$lbl_col_cogs     = $isKm ? 'ដើមទុនសរុប' : 'Total COGS';
$lbl_col_profit   = $isKm ? 'ចំណេញសរុប' : 'Gross Profit';
$lbl_col_margin   = $isKm ? 'កម្រិតចំណេញ %' : 'Margin %';
$lbl_col_sum      = $isKm ? 'សរុប' : 'Total';

$lbl_date_from    = $isKm ? 'ចាប់ពីថ្ងៃ:' : 'Date From:';
$lbl_date_to      = $isKm ? 'ដល់ថ្ងៃ:' : 'Date to';

$lbl_sum_qty      = $isKm ? 'ចំនួនលក់សរុប' : 'Total QTY Sold';
$lbl_sum_disc     = $isKm ? 'បញ្ចុះតម្លៃសរុប' : 'Total Discount';
$lbl_sum_rev      = $isKm ? 'ចំណូលសរុប' : 'Total Revenue';
$lbl_sum_cogs     = $isKm ? 'ដើមទុនសរុប' : 'Total COGS';
$lbl_sum_profit   = $isKm ? 'ប្រាក់ចំណេញសរុប' : 'Total Gross Profit';

// ── Date range calculation ──
$today = business_date_today();
$dateFrom = is_string($_GET['from_date'] ?? $_GET['date_from'] ?? null) ? trim($_GET['from_date'] ?? $_GET['date_from']) : '';
$dateTo   = is_string($_GET['to_date']   ?? $_GET['date_to']   ?? null) ? trim($_GET['to_date']   ?? $_GET['date_to'])   : '';

if (!preg_match('/^\d{4}-\d{2}-\d{2}$/', $dateFrom)) $dateFrom = $today;
if (!preg_match('/^\d{4}-\d{2}-\d{2}$/', $dateTo))   $dateTo   = $today;
if ($dateFrom > $dateTo) [$dateFrom, $dateTo] = [$dateTo, $dateFrom];

$startStr = $dateFrom . ' 00:00:00';
$endStr   = $dateTo   . ' 23:59:59';

// ── Ingredient costs ──
$ingredients = [];
$cost_map_ref = ingredient_cost_map($conn);

// ── Paid orders in range ──
$where_conds = ["DATE(o.order_date) BETWEEN '$dateFrom' AND '$dateTo'", paid_orders_where()];
$filter_payment = trim($_GET['payment_method'] ?? '');
if ($filter_payment !== '') { $where_conds[] = "LOWER(o.payment_method) = '" . $conn->real_escape_string(strtolower($filter_payment)) . "'"; }
$where_str = implode(' AND ', $where_conds);

$qOrders = $conn->query("SELECT o.order_id FROM orders o WHERE $where_str");
$orderIds = [];
if ($qOrders) {
    while ($o = $qOrders->fetch_assoc()) {
        $orderIds[] = (int)$o['order_id'];
    }
}

$topProducts = [];
$totalItemsSold = 0;
$totalSalesRevenue = 0.0;
$totalCOGSAmount = 0.0;
$totalDiscountAmount = 0.0;

$filter_cat = trim($_GET['category'] ?? '');
if (!empty($orderIds)) {
    $inOrder = implode(',', $orderIds);
    $cat_where = '';
    if ($filter_cat !== '') {
        $esc_cat = $conn->real_escape_string($filter_cat);
        $cat_where = " AND (p.category = '$esc_cat' OR oi.category = '$esc_cat')";
    }
    $qItems = $conn->query("
        SELECT oi.product_id, oi.product_name, oi.milk, oi.quantity, oi.price,
               COALESCE(oi.orig_price, oi.price) AS orig_price,
               COALESCE(oi.promo_percent, 0) AS promo_percent,
               COALESCE(NULLIF(p.category,''),'Uncategorized') AS category
        FROM order_items oi
        LEFT JOIN products p ON p.product_id = oi.product_id
        WHERE oi.order_id IN ($inOrder) $cat_where
    ");
    $items = [];
    $productIds = [];
    if ($qItems) {
        while ($it = $qItems->fetch_assoc()) {
            $items[] = $it;
            if ((int)$it['product_id'] > 0) { $productIds[(int)$it['product_id']] = true; }
        }
    }

    $recipes = [];

    foreach ($items as $it) {
        $pid      = (int)$it['product_id'];
        $qty      = max(1, (int)$it['quantity']);
        $milkType = trim((string)$it['milk']);
        $pname    = trim((string)$it['product_name']);
        $category = trim((string)$it['category']) ?: 'Uncategorized';
        $itemCost = 0.0;

        if (isset($recipes[$pid])) {
            foreach ($recipes[$pid] as $rc) {
                $amount = (float)$rc['amount_used'] * $qty;
                if ($amount <= 0) continue;
                if (strpos(strtolower(trim($rc['ingredient_name'])), 'milk') !== false) {
                    $key = strtolower(trim($milkType !== '' ? $milkType : 'Fresh Milk'));
                    if (isset($cost_map_ref[$key])) {
                        $itemCost += $amount * (float)$cost_map_ref[$key]['unit_cost'];
                    }
                } else {
                    $iid = (int)$rc['ingredient_id'];
                    $itemCost += $amount * (float)($cost_map_ref[$iid]['unit_cost'] ?? 0);
                }
            }
        }

        $origPrice = (float)($it['orig_price'] > 0 ? $it['orig_price'] : $it['price']);
        $sellingPrice = (float)($it['price'] ?? 0);
        $promoPct = (float)($it['promo_percent'] ?? 0);
        $itemDiscUnit = 0;
        if ($origPrice > $sellingPrice) {
            $itemDiscUnit = $origPrice - $sellingPrice;
        } elseif ($promoPct > 0) {
            $itemDiscUnit = $sellingPrice * ($promoPct / 100);
        }
        $itemTotalDisc = $itemDiscUnit * $qty;

        $revenue = (float)$it['price'] * $qty;
        $totalItemsSold += $qty;
        $totalSalesRevenue += $revenue;
        $totalCOGSAmount += $itemCost;
        $totalDiscountAmount += $itemTotalDisc;

        if (!isset($topProducts[$pname])) {
            $topProducts[$pname] = [
                'qty'      => 0,
                'cogs'     => 0.0,
                'revenue'  => 0.0,
                'discount' => 0.0,
                'category' => $category
            ];
        }
        $topProducts[$pname]['qty']      += $qty;
        $topProducts[$pname]['cogs']     += $itemCost;
        $topProducts[$pname]['revenue']  += $revenue;
        $topProducts[$pname]['discount'] += $itemTotalDisc;
    }

    uasort($topProducts, fn($a, $b) => $b['revenue'] <=> $a['revenue']);
}

$totalGrossProfit = $totalSalesRevenue - $totalCOGSAmount;

function fmtMoney($amt) {
    return ($amt == floor($amt) ? number_format($amt, 0) : number_format($amt, 2)) . '$';
}
function fmtDisc($amt) {
    if ($amt == 0) return '0';
    return fmtMoney($amt);
}

$processed_rows = [];
$idx = 0;
foreach ($topProducts as $name => $p) {
    $idx++;
    $qty     = (int)$p['qty'];
    $rev     = (float)$p['revenue'];
    $cogs    = (float)$p['cogs'];
    $profit  = $rev - $cogs;
    $margin  = $rev > 0 ? round(($profit / $rev) * 100) : 0;
    $unitPrice = $qty > 0 ? ($rev / $qty) : 0;

    $processed_rows[] = [
        'no'          => $idx,
        'name'        => htmlspecialchars($name),
        'category'    => htmlspecialchars($p['category']),
        'qty'         => $qty,
        'price_cup'   => fmtMoney($unitPrice),
        'discount'    => fmtDisc((float)($p['discount'] ?? 0)),
        'revenue'     => fmtMoney($rev),
        'cogs'        => fmtMoney($cogs),
        'profit'      => fmtMoney($profit),
        'margin'      => $margin . '%',
    ];
}

$fmt_total_disc   = fmtDisc($totalDiscountAmount);
$fmt_total_rev    = fmtMoney($totalSalesRevenue);
$fmt_total_cogs   = fmtMoney($totalCOGSAmount);
$fmt_total_profit = fmtMoney($totalGrossProfit);

// DOMPDF mode check
if (!empty($_GET['dompdf'])) {
    $fontFamily = "'Hanuman', 'Kantumruy Pro', 'Noto Sans Khmer', 'Khmer OS Battambang', 'DejaVu Sans', sans-serif";
    ob_start(); ?>
    <!DOCTYPE html>
    <html>
    <head>
    <meta charset="UTF-8">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Hanuman:wght@400;700&family=Noto+Sans+Khmer:wght@400;700&display=swap" rel="stylesheet">
    <style>
      @import url('https://fonts.googleapis.com/css2?family=Hanuman:wght@400;700&family=Noto+Sans+Khmer:wght@400;700&display=swap');
      @page { margin: 25px 30px; }
      body { font-family: <?= $fontFamily ?>; font-size: 13px; color: #000; margin: 0; line-height: 1.5; }
      .report-header { margin-bottom: 22px; }
      .report-header h1 { font-size: 22px; font-weight: bold; margin: 0 0 5px 0; color: #000; }
      .report-header p { margin: 3px 0; font-size: 13px; color: #000; }
      .section-title { font-size: 13px; font-weight: bold; letter-spacing: 0.5px; margin-bottom: 12px; text-transform: uppercase; color: #000; }
      .report-table { width: 100%; border-collapse: collapse; margin-bottom: 22px; }
      .report-table th, .report-table td { border: 1px solid #000; padding: 6px 5px; text-align: center; font-size: 12px; font-family: <?= $fontFamily ?>; }
      .report-table th { background: #808080; color: #000; font-weight: bold; font-size: 12.5px; white-space: nowrap; }
      .report-table tr.total-row td { font-weight: bold; background: #c6efce; font-size: 12.5px; }
      .summary-footer { font-size: 14px; margin-top: 22px; color: #000; font-family: <?= $fontFamily ?>; line-height: 1.6; }
      .summary-footer p { margin: 0 0 10px 0; font-size: 14px; font-weight: normal; }
      .summary-footer .sum-item { margin: 4px 0; font-size: 14px; }
      .summary-footer .sum-item b { display: inline-block; width: 140px; }
    </style>
    </head>
    <body>
    <div class="report-header">
      <h1><?= he($lbl_cafe_title) ?></h1>
      <p><?= he($lbl_report_prod) ?></p>
      <p><?= he($lbl_period) ?> <?= he($dateFrom) ?> <?= he($lbl_to) ?> <?= he($dateTo) ?></p>
      <p><?= he($lbl_generated) ?> <?= date('j/n/Y, g:i:s A') ?></p>
      <p><?= he($lbl_generated_by) ?> <?= he($_SESSION['username'] ?? 'Admin') ?></p>
    </div>
    <div class="section-title"><?= he($lbl_table_title) ?></div>
    <table class="report-table">
      <thead>
        <tr>
          <th style="width:8%;"><?= he($lbl_col_no) ?></th>
          <th style="width:44%;"><?= he($lbl_col_pname) ?></th>
          <th style="width:14%;"><?= he($lbl_col_qty) ?></th>
          <th style="width:16%;"><?= he($lbl_col_price) ?></th>
          <th style="width:18%;"><?= he($lbl_col_rev) ?></th>
        </tr>
      </thead>
      <tbody>
        <?php if (empty($processed_rows)): ?>
          <tr><td colspan="5" style="text-align:center; padding:14px"><?= $isKm ? 'គ្មានទិន្នន័យទំនិញឡើយ' : 'No product sales data found for selected period.' ?></td></tr>
        <?php else: foreach ($processed_rows as $r): ?>
          <tr>
            <td><?= $r['no'] ?></td>
            <td style="text-align:left; padding-left:8px;"><?= $r['name'] ?></td>
            <td><?= $r['qty'] ?></td>
            <td><?= $r['price_cup'] ?></td>
            <td><?= $r['revenue'] ?></td>
          </tr>
        <?php endforeach; ?>
          <tr class="total-row">
            <td colspan="2" style="text-align:center; background:#c6efce;"><?= he($lbl_col_sum) ?></td>
            <td style="background:#c6efce;"><?= $totalItemsSold ?></td>
            <td style="background:#fff;"></td>
            <td style="background:#c6efce;"><?= $fmt_total_rev ?></td>
          </tr>
        <?php endif; ?>
      </tbody>
    </table>
    <div class="summary-footer">
      <p><?= he($lbl_date_from) ?> <?= he(date('j/n/Y', strtotime($dateFrom))) ?> <?= he($lbl_date_to) ?> <?= he(date('j/n/Y', strtotime($dateTo))) ?></p>
      <div class="sum-item"><b><?= he($lbl_sum_qty) ?></b> : <b><?= $totalItemsSold ?></b> Item</div>
      <div class="sum-item"><b><?= he($lbl_sum_rev) ?></b> : <b><?= $fmt_total_rev ?></b></div>
    </div>
    </body>
    </html>
    <?php
    $html = ob_get_clean();
    $options = new Options();
    $options->set('isRemoteEnabled', true);
    $options->set('defaultFont', 'Hanuman');
    $dompdf = new Dompdf($options);
    $dompdf->loadHtml($html, 'UTF-8');
    $dompdf->setPaper('A4', 'portrait');
    $dompdf->render();
    $dompdf->stream(('product-report-' . $dateFrom . '-' . $dateTo) . '.pdf', ['Attachment' => false]);
    exit;
}
?>
<!DOCTYPE html>
<html lang="<?= $isKm ? 'km' : 'en' ?>">
<head>
<meta charset="UTF-8">
<title><?= he($lbl_report_prod) ?> - <?= he($dateFrom) ?> <?= he($lbl_to) ?> <?= he($dateTo) ?></title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Hanuman:wght@400;700&family=Kantumruy+Pro:wght@400;700&family=Noto+Sans+Khmer:wght@400;700&display=swap" rel="stylesheet">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Hanuman:wght@400;700&family=Kantumruy+Pro:wght@400;700&family=Noto+Sans+Khmer:wght@400;700&display=swap');

  @page { margin: 0; size: A4 portrait; }
  
  body {
    font-family: 'Hanuman', 'Kantumruy Pro', 'Noto Sans Khmer', 'Khmer OS Battambang', 'Khmer OS Siemreap', 'DejaVu Sans', 'Times New Roman', serif;
    font-size: 14px;
    color: #000000;
    margin: 0;
    padding: 20px;
    background: #ffffff;
    line-height: 1.55;
  }

  .no-print-bar {
    position: fixed;
    top: 0;
    left: 0;
    right: 0;
    background: #18181b;
    color: #ffffff;
    padding: 10px 24px;
    display: flex;
    align-items: center;
    justify-content: space-between;
    z-index: 9999;
    box-shadow: 0 4px 12px rgba(0,0,0,0.35);
    font-family: system-ui, -apple-system, sans-serif;
  }
  .no-print-bar .btn {
    background: #d1904b;
    color: #000;
    font-weight: 700;
    border: none;
    padding: 8px 18px;
    border-radius: 6px;
    cursor: pointer;
    font-size: 13px;
    text-decoration: none;
    display: inline-flex;
    align-items: center;
    gap: 6px;
  }
  .no-print-bar .btn-secondary {
    background: #3f3f46;
    color: #fff;
  }

  * {
    -webkit-print-color-adjust: exact !important;
    print-color-adjust: exact !important;
  }

  @media print {
    * {
      -webkit-print-color-adjust: exact !important;
      print-color-adjust: exact !important;
    }
    .no-print-bar { display: none !important; }
    body { padding: 15mm 20mm !important; margin: 0 !important; }
    .report-wrapper { margin: 0 auto; max-width: 100%; }
    .report-table th {
      background-color: #808080 !important;
      -webkit-print-color-adjust: exact !important;
      print-color-adjust: exact !important;
    }
    .report-table tr.total-row td {
      -webkit-print-color-adjust: exact !important;
      print-color-adjust: exact !important;
    }
  }

  .report-wrapper {
    max-width: 820px;
    margin: 50px auto 0;
  }

  .report-header { margin-bottom: 22px; }
  .report-header h1 { font-size: 24px; font-weight: bold; margin: 0 0 5px 0; color: #000; }
  .report-header p { margin: 3px 0; font-size: 14px; color: #000; }
  .section-title { font-size: 14px; font-weight: bold; letter-spacing: 0.5px; margin-bottom: 12px; text-transform: uppercase; color: #000; }
  .report-table { width: 100%; border-collapse: collapse; margin-bottom: 22px; }
  .report-table th, .report-table td { border: 1px solid #000; padding: 6px 5px; text-align: center; font-size: 13px; }
  .report-table th {
    background-color: #808080 !important;
    color: #000 !important;
    font-weight: bold;
    font-size: 13.5px;
    white-space: nowrap;
    -webkit-print-color-adjust: exact !important;
    print-color-adjust: exact !important;
  }
  .report-table tr.total-row td { font-weight: bold; font-size: 13.5px; }
  
  .summary-footer { font-size: 14px; margin-top: 22px; color: #000; line-height: 1.6; }
  .summary-footer p { margin: 0 0 10px 0; font-size: 14px; font-weight: normal; }
  .summary-footer .sum-item { margin: 5px 0; font-size: 15px; }
  .summary-footer .sum-item b.lbl { display: inline-block; min-width: 150px; font-weight: bold; }
</style>
</head>
<body>

<div class="no-print-bar">
  <div style="font-size:14px; font-weight:600;">
    <?= $isKm ? 'មើលរបាយការណ៍បោះពុម្ព (Product Print Preview)' : 'Product Report Print Preview' ?>
  </div>
  <div style="display:flex; gap:10px;">
    <button class="btn" onclick="window.print()">
      🖨️ <?= $isKm ? 'បោះពុម្ពឥឡូវនេះ (Print Now)' : 'Print Now' ?>
    </button>
    <a href="<?= htmlspecialchars($_SERVER['REQUEST_URI']) ?>&dompdf=1" class="btn btn-secondary">
      📄 <?= $isKm ? 'ទាញយក PDF (Download PDF)' : 'Download PDF' ?>
    </a>
  </div>
</div>

<div class="report-wrapper">
  <div class="report-header">
    <h1><?= he($lbl_cafe_title) ?></h1>
    <p><?= he($lbl_report_prod) ?></p>
    <p><?= he($lbl_period) ?> <?= he($dateFrom) ?> <?= he($lbl_to) ?> <?= he($dateTo) ?></p>
    <p><?= he($lbl_generated) ?> <?= date('j/n/Y, g:i:s A') ?></p>
    <p><?= he($lbl_generated_by) ?> <?= he($_SESSION['username'] ?? 'Admin') ?></p>
  </div>

  <div class="section-title"><?= he($lbl_table_title) ?></div>

  <table class="report-table">
    <thead>
      <tr>
        <th style="width:8%;"><?= he($lbl_col_no) ?></th>
        <th style="width:44%;"><?= he($lbl_col_pname) ?></th>
        <th style="width:14%;"><?= he($lbl_col_qty) ?></th>
        <th style="width:16%;"><?= he($lbl_col_price) ?></th>
        <th style="width:18%;"><?= he($lbl_col_rev) ?></th>
      </tr>
    </thead>
    <tbody>
      <?php if (empty($processed_rows)): ?>
        <tr><td colspan="5" style="text-align:center; padding:14px"><?= $isKm ? 'គ្មានទិន្នន័យទំនិញឡើយ' : 'No product sales data found for selected period.' ?></td></tr>
      <?php else: foreach ($processed_rows as $r): ?>
        <tr>
          <td><?= $r['no'] ?></td>
          <td style="text-align:left; padding-left:8px;"><?= $r['name'] ?></td>
          <td><?= $r['qty'] ?></td>
          <td><?= $r['price_cup'] ?></td>
          <td><?= $r['revenue'] ?></td>
        </tr>
      <?php endforeach; ?>
        <tr class="total-row">
          <td colspan="2" style="text-align:center; background:#c6efce;"><?= he($lbl_col_sum) ?></td>
          <td style="background:#c6efce;"><?= $totalItemsSold ?></td>
          <td style="background:#fff;"></td>
          <td style="background:#c6efce;"><?= $fmt_total_rev ?></td>
        </tr>
      <?php endif; ?>
    </tbody>
  </table>

  <div class="summary-footer">
    <p><?= he($lbl_date_from) ?> <?= he(date('j/n/Y', strtotime($dateFrom))) ?> <?= he($lbl_date_to) ?> <?= he(date('j/n/Y', strtotime($dateTo))) ?></p>
    <div class="sum-item"><b class="lbl"><?= he($lbl_sum_qty) ?></b> : <b><?= $totalItemsSold ?></b> Item</div>
    <div class="sum-item"><b class="lbl"><?= he($lbl_sum_rev) ?></b> : <b><?= $fmt_total_rev ?></b></div>
  </div>
</div>

<script>
window.addEventListener('DOMContentLoaded', () => {
  // Automatically trigger print dialog when page finishes loading
  setTimeout(() => { window.print(); }, 400);
});
</script>
</body>
</html>
